### PR TITLE
Add an endpoint to query for photometry taken on certain instruments over a time range

### PR DESCRIPTION
**Pull request by dannygoldstein**
Addresses #949 (for photometry).

@cfremling.

This PR adds the following new endpoint:

Screen Shot 2020-09-26 at 8 47 21 PM

### CODE REVIEW

**Review by profjsb — APPROVED** [review]
Looks very good. My only suggestion would be to change the endpoint from `/recent/` to something else: there is nothing in the capability that requires the photometry to be recent. Maybe `/range/'? Change the handler names accordingly.

**Review by guynir42 — APPROVED** [review]
LGTM!

**Comment by dannygoldstein** [comment]
> Looks very good. My only suggestion would be to change the endpoint from `/recent/` to something else: there is nothing in the capability that requires the photometry to be recent. Maybe `/range/'? Change the handler names accordingly.

Fixed

**Comment by dannygoldstein** [comment]
This is ready for a relook @profjsb

**Comment by dannygoldstein** [comment]
Ping @profjsb

**Pull request merged**
