### PR TITLE
Add includeComments (default = false) query param to sources API and never include attachment data

### PR DESCRIPTION
**Pull request by acrellin**
This PR adds an optional `includeComments` query parameter to `SourceHandler.get` which defaults to `False`, and never ships comment attachment bytes.

Closes https://github.com/skyportal/skyportal/issues/1464

### CODE REVIEW

**Review by dmitryduev — APPROVED** [review]
Looks good, thanks @acrellin !

**Comment by stefanv** [comment]
Can we avoid downloading all attachments by default when loading a source?  I feel like those should only be grabbed when requested.  Otherwise this is :+1:

**Comment by acrellin** [comment]
@stefanv by default when loading a source, the comments are not loaded unless done so manually. Here we're loading the comments manually, and conditionally including the `attachment_name` and `attachment_bytes` columns when doing so.

**Review by stefanv — APPROVED** [review]

**Review by kmshin1397 — APPROVED** [review]

**Comment by kmshin1397** [comment]
I think this is good to merge on green :)

**Pull request merged**
