### PR TITLE
Include creation time of oldest unsaved candidate on DB Stats page

### PR DESCRIPTION
**Pull request by acrellin**

### CODE REVIEW

**Comment by dannygoldstein** [comment]
What's the motivation for this feature ?

**Review by dannygoldstein — APPROVED** [review]

**Comment by acrellin** [comment]
To ensure that the deletion of old unsaved candidates is being done
correctly

**Comment by stefanv** [comment]
I don't quite follow—how does this relate to deletion?

**Comment by dmitryduev** [comment]
@stefanv old unsaved candidates should be vacuumed; displaying this will tell us when something is wrong. The page is current displaying the oldest candidate in the db, but that may or may not have been saved, so not very informative.

**Comment by stefanv** [comment]
Oh, I thought there was some deeper hidden meaning :)  Yes, that makes good sense, thanks for the explanation Dima.

**Pull request merged**
