### PR TITLE
User affiliations

### PR DESCRIPTION
**Pull request by Theodlz**
This PR is a work in progress, that is based on the changes made on this baselayer PR: https://github.com/cesium-ml/baselayer/pull/328

This adds the backend and frontend to create users with affiliations, as well as modifying them (both by an admin and the users themselves). Compared to username, first name and last name that can't be edited by an admin via the frontend, here, in the UserManagement Menu, I added the possibility to edit the affiliations of users. This is because an error in the way they are written could be a problem when using the user's affiliation to automatically generate circulars for example. Allowing the admin to edit it seemed useful to me.

### CODE REVIEW

**Review by guynir42 — APPROVED** [review]
Minor comments below:

**Comment by guynir42** [comment]
@Theodlz I think strategically we should merge this after this week's deploy. 
The migrations may turn out to be tricky if we need to roll back and I won't be around this weekend to take care of it. 
Also I don't think this is super urgent, so merging after the deploy is my preference.

**Comment by mcoughlin** [comment]
@guynir42 Shall we merge?

**Comment by guynir42** [comment]
@mcoughlin go for it.

**Pull request merged**
