### PR TITLE
If initialState.allowed_classes is null, return loading message in ClassificationForm

### PR DESCRIPTION
**Pull request by acrellin**
@profjsb @stefanv there seems to be an underlying data issue as well that this PR does not address: in `ClassificationForm`, even when `taxonomyList[0]` is not null, the `allowed_classes` attribute that the front-end expects is not present (after running `make load_demo_data`). Just a heads up. I can break that out into an issue.

### CODE REVIEW

**Comment by stefanv** [comment]
@acrellin I think this is due to my unfamiliarity with the reducer logic.  Shouldn't the allowed classes always be set to something?

Once the length of the list is >0, the allowed classes should be computable immediately; so why can't we render the component then?

**Comment by acrellin** [comment]
@stefanv my initial comment explains it: the elements of the taxonomy list fetched from the backend are expected to have an allowed_classes attribute, but it is missing.

**Comment by stefanv** [comment]
@acrellin We removed that on purpose, so anything that expects that should be changed. The allowed classes are now computed on the frontend.

**Comment by acrellin** [comment]
> @acrellin We removed that on purpose, so anything that expects that should be changed. The allowed classes are now computed on the frontend.

Okay -- @profjsb can you update the ClassificationForm component accordingly, then?

**Comment by stefanv** [comment]
Closing since #674 was merged; thanks for this PR, Ari.

**Pull request closed without merging**
