### PR TITLE
mark analysis test as flaky

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR adds retries for the analysis test, which is flaky.

### CODE REVIEW

**Review by guynir42 — APPROVED** [review]
I would try to figure out what is the underlying causes for all this flakiness. But for now this is fine.

**Review by guynir42 — CHANGES_REQUESTED** [review]
Actually this is not solving the underlying problem. This test never passes, no matter the retries.

**Comment by mcoughlin** [comment]
@guynir42 Let's move it to flaky? Seems fine locally.

**Comment by guynir42** [comment]
That's fine but make an issue about it. We can't just sweep tests under the carpet.

**Pull request merged**
