### PR TITLE
Add whitelisted IPs section to config

### PR DESCRIPTION
**Pull request by acrellin**

### CODE REVIEW

**Review by dmitryduev — APPROVED** [review]

**Comment by stefanv** [comment]
Should we also parameterize the burst rate etc.?

**Comment by acrellin** [comment]
> Should we also parameterize the burst rate etc.?

This is the wrong place for that, but sure, I'll add those in baselayer

**Comment by stefanv** [comment]
Yeah, not urgent either. This is good to go.

**Comment by acrellin** [comment]
Merging with two approvals, failure unrelated: `FAILED skyportal/tests/api/test_photometry.py::test_token_user_big_post - ass...`

**Pull request merged**
