### PR TITLE
Pin confluent-kafka

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR pins confluent-kafka to the latest version, suggested by Leo to understand gcn memory requirements.

### CODE REVIEW

**Comment by stefanv** [comment]
Is this a dependency of gcn-kafka?

**Comment by mcoughlin** [comment]
@stefanv yes.

**Comment by stefanv** [comment]
Let's move it down to underneath gcn-kafka then, and add a comment explaining why it is being pinned.

**Review by stefanv — APPROVED** [review]

**Review by guynir42 — APPROVED** [review]
LGTM

**Pull request merged**
