### PR TITLE
Reject candidates

### PR DESCRIPTION
**Pull request by guynir42**
Let the user click a single button to reject a candidate. 
The candidate will no longer show up on the scanning page. 
An option to show all candidates, including those rejected, is set to false by default. 
This uses the Listing table, in a very similar way to "favorites". 

reject_candidates

### CODE REVIEW

**Review by dmitryduev — COMMENTED** [review]
Thanks for the quick implementation @guynir42! As we have discussed, I think this would be more widely applicable if implemented at at the Candidate (Obj x Filter) level (I'd add a "hidden" column to Candidate; this may have to be "broadcast" to all Candidates for a given (Obj, Filter) pair). Consequently, there should be a toggle switch (or better a super complicated dropdown menu to cover all possible cases ;-) ) to display/hide candidates marked as hidden in selected groups.

**Comment by guynir42** [comment]
> Thanks for the quick implementation @guynir42! As we have discussed, I think this would be more widely applicable if implemented at at the Candidate (Obj x Filter) level (I'd add a "hidden" column to Candidate; this may have to be "broadcast" to all Candidates for a given (Obj, Filter) pair). Consequently, there should be a toggle switch (or better a super complicated dropdown menu to cover all possible cases ;-) ) to display/hide candidates marked as hidden in selected groups.

This is fairly straightforward to implement, I think. But there is an issue with having user A trust that user B to hide away candidates for them. Consider that B maybe shares only some of the groups/filters with A. 
It is always possible to show the hidden candidates, but at some point you have to trust the other users that are hiding candidates, otherwise you will spend just the same amount of time scanning the hidden ones. 

I think this is not so simple. I also think that the current implementation is useful on its own. 
Perhaps we should merge it and open for discussion more advanced ways to reject candidates in a different issue/PR?

**Review by kmshin1397 — COMMENTED** [review]
@guynir42 Do you want to merge in the latest master here to let the CI run fully? Just want to make sure, but this looks good. Thanks!

**Comment by guynir42** [comment]
@kmshin1397 @dmitryduev all tests are now green...

**Review by dmitryduev — APPROVED** [review]

**Review by dmitryduev — CHANGES_REQUESTED** [review]
Oh, actually one small ui request: could you please align the icon with the previously saved/not saved tag and enforce it to be on the same line? (prob making it smaller too)

**Comment by guynir42** [comment]
> Oh, actually one small ui request: could you please align the icon with the previously saved/not saved tag and enforce it to be on the same line? (prob making it smaller too)

When the object is saved to multiple groups there are a few chips of "previously saved to" so where should the reject button go in that case?  @dmitryduev

**Comment by guynir42** [comment]
@dmitryduev ok I think I got it... but is there any way to force it to not break the line?

**Review by kmshin1397 — APPROVED** [review]

**Comment by guynir42** [comment]
The test failure seems unrelated...

**Review by dmitryduev — APPROVED** [review]
👍🏻

**Pull request merged**
