### PR TITLE
Refactor comment author to be User instead of User.username

### LINKED ISSUE #852: Comment author logic needs updating -- username is now changeable
```
ERROR:tornado.application:Uncaught exception GET /api/newsfeed (127.0.0.1)                                                             
HTTPServerRequest(protocol='http', host='localhost:5000', method='GET', uri='/api/newsfeed', version='HTTP/1.0', remote_ip='127.0.0.1')
Traceback (most recent call last):                                                                                                     
  File "/home/arien/anaconda3/envs/skyportal38/lib/python3.8/site-packages/tornado/web.py", line 1697, in _execute                     
    result = method(*self.path_args, **self.path_kwargs)                                                                               
  File "/home/arien/projects/skyportal/baselayer/app/access.py", line 32, in wrapper                                                   
    return tornado.web.authenticated(method)(self, *args, **kwargs)                                                                    
  File "/home/arien/anaconda3/envs/skyportal38/lib/python3.8/site-packages/tornado/web.py", line 3174, in wrapper                      
    return method(self, *args, **kwargs)                                                                                               
  File "/home/arien/projects/skyportal/skyportal/handlers/api/news_feed.py", line 72, in get                                           
    comments = fetch_newest(Comment)                                                                                                   
  File "/home/arien/projects/skyportal/skyportal/handlers/api/news_feed.py", line 67, in fetch_newest                                  
    comment.author_info = comment.construct_author_info_dict()                                                                         
  File "/home/arien/projects/skyportal/skyportal/models.py", line 1256, in construct_author_info_dict                                  
    return {                                                                                                                           
  File "/home/arien/projects/skyportal/skyportal/models.py", line 1257, in <dictcomp>                                                  
    field: getattr(user, field)                                                                                                        
AttributeError: 'NoneType' object has no attribute 'username'                                                                          
[!] Error in `/api/newsfeed`: 'NoneType' object has no attribute 'username'                                                            
WARNING:tornado.access:400 GET /api/newsfeed (127.0.0.1) 21.81ms            
```

### PR DESCRIPTION
**Pull request by acrellin**
Closes #852

### CODE REVIEW

**Review by stefanv — APPROVED** [review]

**Review by kmshin1397 — CHANGES_REQUESTED** [review]
https://github.com/skyportal/skyportal/blob/9f11080cf98f294add382e6405a22de6d52f37bf/skyportal/models.py#L784

I think you need to refactor the get_obj_comments_owned_by() function as well. The reason I introduced the get_author_info_dict() method was to avoid leaking comment author contact info, but with the change that information is included in the comment.author field and available to be seen in the redux store for anyone with access to a source.

**Comment by acrellin** [comment]
> https://github.com/skyportal/skyportal/blob/9f11080cf98f294add382e6405a22de6d52f37bf/skyportal/models.py#L784
> 
> I think you need to refactor the get_obj_comments_owned_by() function as well. The reason I introduced the get_author_info_dict() method was to avoid leaking comment author contact info, but with the change that information is included in the comment.author field and available to be seen in the redux store for anyone with access to a source.

@kmshin1397 Would that be just to preserve privacy, or because you think it'll error somewhere? If the former, we just recently changed our approach to that -- anyone is now able to see everyone else's profile info, etc. Does that address your concern, or is it something else?

**Comment by kmshin1397** [comment]
@acrellin Yeah that was for privacy, so I guess that concern is address. But that does make the author_info field a bit redundant I believe, since all that info but the gravitar url is in author now. But that can be part of the redux store refactor we have storied for later anyways.

**Review by kmshin1397 — APPROVED** [review]

**Comment by stefanv** [comment]
We should also disable react logging to the console in production mode.

**Pull request merged**
