### PR TITLE
Periodogram

### PR DESCRIPTION
**Pull request by profjsb**
See this [release video](https://berkeley.box.com/s/t2tif50884bac3qus4yhui08rfggczt7) for a preview of the features.

Reinstates the PR from #1633. Fixes for staging errors with multiple instruments.

### CODE REVIEW

**Comment by stefanv** [comment]
@profjsb Could you explain the concept of an established filter?

**Comment by profjsb** [comment]
> @profjsb Could you explain the concept of an established filter?

It's a boolean that captures whether the instrument and filter list has been loaded from the available photometry.

**Comment by profjsb** [comment]
Addresses @acrellin's PR feedback in #1633.

**Review by acrellin — APPROVED** [review]
Looks good, thanks @profjsb

**Comment by scizen9** [comment]
I'm seeing some conflicting behaviour.  When I select a time range, it calculates a new period automatically.
Hitting the 'Recalculate' button actually resets the time range to the entire data set and recalculates a new
period.  I would relabel the button 'Reset Range' and change the instructions to indicate that a new period is
calculated as soon as you select a time range.

**Review by scizen9 — CHANGES_REQUESTED** [review]
I think I understand now.  The 'Recalculate' button is for the parameters, not for the period range.  As written, I thought I would select the range and then hit the button.  Just need to clarify the different behaviour for the parameters and the range in the text.

**Review by kmshin1397 — COMMENTED** [review]
Looks good, @profjsb! The one issue I have is that the value displays on hover for each point are hard to see on the phased plots as it overlaps with the plot title. I took a quick glance through the Dygraphs documented options and it didn't seem like there was an easy way to move that hover display to the upper right corner instead of the upper left. Or perhaps we can add some `padding-bottom` to the plot title so that there isn't an overlap with the values?
image

**Comment by profjsb** [comment]
> Looks good, @profjsb! The one issue I have is that the value displays on hover for each point are hard to see on the phased plots as it overlaps with the plot title. I took a quick glance through the Dygraphs documented options and it didn't seem like there was an easy way to move that hover display to the upper right corner instead of the upper left. Or perhaps we can add some `padding-bottom` to the plot title so that there isn't an overlap with the values?
> image

Fixed this by suppressing the legend (not really needed here for the workflow).

**Comment by profjsb** [comment]
> I think I understand now. The 'Recalculate' button is for the parameters, not for the period range. As written, I thought I would select the range and then hit the button. Just need to clarify the different behaviour for the parameters and the range in the text.
@scizen9 made some formatting changes to address your concern.
image

**Review by scizen9 — APPROVED** [review]
This does the trick for me.

**Pull request merged**
