### PR TITLE
coerce spectrum flux,fluxerr,wave to floats

### LINKED ISSUE #1188: upload spectra fails for integer wavelengths
I tried to upload a dummy spectra using integer values for lambda. 

The preview rendered fine, but failed to upload. 

When I added decimal point (4000-> 4000.0) the problem went away. 

Error I got from log: 

`ERROR:tornado.application:Uncaught exception POST /api/spectrum/ascii (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/api/spectrum/ascii', version='HTTP/1.0', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: can't adapt type 'numpy.int64'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/tornado/web.py", line 1697, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/guyn/skyportal/baselayer/app/access.py", line 32, in wrapper
    return tornado.web.authenticated(method)(self, *args, **kwargs)
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/tornado/web.py", line 3174, in wrapper
    return method(self, *args, **kwargs)
  File "/home/guyn/skyportal/baselayer/app/access.py", line 51, in wrapper
    return method(self, *args, **kwargs)
  File "/home/guyn/skyportal/skyportal/handlers/api/spectrum.py", line 315, in post
    obj = Source.get_obj_if_owned_by(json['obj_id'], self.current_user)
  File "/home/guyn/skyportal/skyportal/models.py", line 898, in get_source_if_owned_by
    if Source.query.filter(Source.obj_id == obj_id).first() is None:
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3232, in first
    ret = list(self[0:1])
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3018, in __getitem__
    return list(res)
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3333, in __iter__
    self.session._autoflush()
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1588, in _autoflush
    util.raise_from_cause(e)
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1577, in _autoflush
    self.flush()
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2459, in flush
    self._flush(objects)
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2557, in _flush
    flush_context.execute()
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1137, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self._handle_dbapi_exception(
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/home/guyn/skyportal/skyportal_env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.ProgrammingError) can't adapt type 'numpy.int64'
[SQL: INSERT INTO spectra (created_at, modified, wavelengths, fluxes, errors, obj_id, observed_at, origin, instrument_id, followup_request_id, assignment_id, altdata, original_file_string, original_file_filename, owner_id) VALUES (timezone(%(timezone_1)s, CURRENT_TIMESTAMP), timezone(%(timezone_1)s, CURRENT_TIMESTAMP), %(wavelengths)s, %(fluxes)s, %(errors)s, %(obj_id)s, %(observed_at)s, %(origin)s, %(instrument_id)s, %(followup_request_id)s, %(assignment_id)s, %(altdata)s, %(original_file_string)s, %(original_file_filename)s, %(owner_id)s) RETURNING spectra.id]
[parameters: {'timezone_1': 'UTC', 'wavelengths': [4000, 4500, 5000, 5500, 6000], 'fluxes': [0.01, 0.02, 0.005, 0.006, 0.01], 'errors': None, 'obj_id': '14gqr', 'observed_at': datetime.datetime(1875, 4, 22, 0, 0, tzinfo=datetime.timezone.utc), 'origin': None, 'instrument_id': 3, 'followup_request_id': None, 'assignment_id': None, 'altdata': 'null', 'original_file_string': '4000 0.01\n4500 0.02\n5000 0.005\n5500 0.006\n6000 0.01\n', 'original_file_filename': None, 'owner_id': 4}]
(Background on this error at: http://sqlalche.me/e/f405)
[17:29:44 basehandler] Error response returned by [/api/spectrum/ascii]: [(raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.ProgrammingError) can't adapt type 'numpy.int64'
[SQL: INSERT INTO spectra (created_at, modified, wavelengths, fluxes, errors, obj_id, observed_at, origin, instrument_id, followup_request_id, assignment_id, altdata, original_file_string, original_file_filename, owner_id) VALUES (timezone(%(timezone_1)s, CURRENT_TIMESTAMP), timezone(%(timezone_1)s, CURRENT_TIMESTAMP), %(wavelengths)s, %(fluxes)s, %(errors)s, %(obj_id)s, %(observed_at)s, %(origin)s, %(instrument_id)s, %(followup_request_id)s, %(assignment_id)s, %(altdata)s, %(original_file_string)s, %(original_file_filename)s, %(owner_id)s) RETURNING spectra.id]
[parameters: {'timezone_1': 'UTC', 'wavelengths': [4000, 4500, 5000, 5500, 6000], 'fluxes': [0.01, 0.02, 0.005, 0.006, 0.01], 'errors': None, 'obj_id': '14gqr', 'observed_at': datetime.datetime(1875, 4, 22, 0, 0, tzinfo=datetime.timezone.utc), 'origin': None, 'instrument_id': 3, 'followup_request_id': None, 'assignment_id': None, 'altdata': 'null', 'original_file_string': '4000 0.01\n4500 0.02\n5000 0.005\n5500 0.006\n6000 0.01\n', 'original_file_filename': None, 'owner_id': 4}]
(Background on this error at: http://sqlalche.me/e/f405)]
WARNING:tornado.access:400 POST /api/spectrum/ascii (127.0.0.1) 16.77ms
- - - [27/Oct/2020:17:29:44 +0200] "POST /api/spectrum/ascii HTTP/1.1" 400 1398 "http://localhost:5000/upload_spectrum/14gqr" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0"`

### PR DESCRIPTION
**Pull request by dannygoldstein**
Fixes #1188 and adds a test.

### CODE REVIEW

**Review by guynir42 — APPROVED** [review]

**Comment by dannygoldstein** [comment]
@guynir42 please go ahead and merge

**Comment by guynir42** [comment]
I think I don't have this option for some reason...

**Comment by dannygoldstein** [comment]
@guynir42 squash and merge

**Comment by dannygoldstein** [comment]
Screen Shot 2020-10-30 at 12 12 48 PM

**Pull request merged**
