### PR TITLE
Draft: GRANDMA Contribution: Add files for db provision and first Dashboard Page

### PR DESCRIPTION
**Pull request by julietteBrt**
Two aspects of this PR:

- Creation of python scripts to add GRANDMA's data from owncloud.
- First dashboard page --> issue with the display of the skymap: TypeError: window.A is undefined, file: Aladin.jsx
Works fine on a standalone application, see https://github.com/nvermaas/react-aladin-example/blob/master/src/pages/asteroids/Aladin.jsx from where the code is inspired.

For now the features of the skymap are hard-coded, to fix the basic display, front-end is not linked to back-end.

### CODE REVIEW

**Comment by mcoughlin** [comment]
@julietteBrt Would you mind posting a screenshot of your ListAlerts.jsx component here?

**Comment by julietteBrt** [comment]
shifts
ListofShifts.jsx Component

**Comment by mcoughlin** [comment]
@julietteBrt I meant your fancy alert table which is also in there right?

**Comment by mcoughlin** [comment]
closing this as the capabilities are now in other PRs. @Theodlz just tagging you to keep track of anything else you need from here.

**Pull request closed without merging**
