### PR TITLE
Serialize console logs  as artifacts on test failure

### PR DESCRIPTION
**Pull request by dannygoldstein**
This PR extracts the firefox console output (including redux state and actions) from `geckodriver.log` and, on test failures, serializes it to a file in `test-results` for each test, similar to the `.html` page state and screenshots on failure.

### CODE REVIEW

**Comment by dannygoldstein** [comment]
It works! And the failures are unrelated.

**Comment by dannygoldstein** [comment]
I am going to push one final change, splitting this off from `test-results` into another directory. The redux state logs are fairly large (they contain 2x the entire application state for each new log item - about 10MB per test) so I think developers should have the option of downloading those separately from the other lighter weight test results

**Comment by stefanv** [comment]
@dannygoldstein Why don't we throw away all entries for successful tests?

**Comment by dannygoldstein** [comment]
Where? In the geckodriver log, or the artifact?

**Comment by dannygoldstein** [comment]
I added some code to truncate the geckodriver log. This needs a merge of https://github.com/cesium-ml/baselayer/pull/173 into baselayer master to merge

**Review by acrellin — APPROVED** [review]

**Comment by dannygoldstein** [comment]
this is ready to go - failures are unrelated to this PR (new failures are related to https://github.com/cesium-ml/baselayer/pull/175)

**Review by stefanv — APPROVED** [review]

**Pull request merged**
