### PR TITLE
Download tests fail

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR moves download tests to flaky.

### CODE REVIEW

**Comment by guynir42** [comment]
@mcoughlin I just have a bad feeling that if we do this now, we will never get back to these tests.

**Comment by mcoughlin** [comment]
Merging for now, ready to revert once ACT tells us what is up with the file download on GA. @bfhealy

**Comment by bfhealy** [comment]
@mcoughlin I've worked through a few install errors with act/skyportal and it seems to have the app running now. I'll let you know what happens as the local frontend tests run.

**Comment by bfhealy** [comment]
@mcoughlin The frontend part 1 and 2 tests are both failing locally; it seems to be a server issue with localhost since pytest was not yet launched. Here's some of the log from the latest run:

```
[API & frontend/test-3] ⭐ Run Main Run front-end tests part 2
[API & frontend/test-3]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/18] user= workdir=
|   Config files: baselayer/config.yaml.defaults
|                 config.yaml.defaults
| [16:36:44 test_frontend] Connecting to test database
|   Config files: baselayer/config.yaml.defaults
|                 config.yaml.defaults
|                 test_config.yaml
| [16:36:45 test_frontend] Clearing test database...
| Dropping tables on database skyportal_test
| Creating tables on database skyportal_test
| Refreshed tables: acls, roles, role_acls, users, user_acls, tokens, token_acls, user_roles, cronjobruns, usersocialauths, nonces, associations, codes, partials
| 
| [16:36:46 test_frontend] Waiting for server to appear at http://localhost:5000...
| 
| Welcome to SkyPortal v0.9.dev0+git20221214.51c34650 (https://skyportal.io)
| 
| Checking system dependencies:
[✓] nginx >= 1.7.7                  [  1.18.0]
[✓] psql >= 12.0.0                  [   12.12]
[✓] npm >= 8.3.2.2                  [  8.19.2]
[✓] node >= 16.14.0.0               [ 16.18.1]
[✓] python >= 3.8.8                 [  3.8.15]
| 
[✓] Baselayer installed inside of apppp
| --------------------
[✓] Verifying Python package dependencieses
[✓] Silently executing: baselayer/tools/check_js_deps.shsh
[✓] Silently executing: baselayer/tools/check_js_deps.shsh
[API & frontend/test-2]   ✅  Success - Main Refresh SkyPortal dependencies for tested version
[API & frontend/test-2] ⭐ Run Main Patch test_frontend.py for a longer timeout
[API & frontend/test-2]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/15] user= workdir=
[API & frontend/test-2]   ✅  Success - Main Patch test_frontend.py for a longer timeout
[API & frontend/test-2] ⭐ Run Main Patch Notifications.jsx for a longer display
[API & frontend/test-2]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/16] user= workdir=
[API & frontend/test-2]   ✅  Success - Main Patch Notifications.jsx for a longer display
[API & frontend/test-2] ⭐ Run Main Run front-end tests part 1
[API & frontend/test-2]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/17] user= workdir=
| [16:37:13 baselayer] Compiling configuration templates
|   Config files: baselayer/config.yaml.defaults
|                 config.yaml.defaults
|                 test_config.yaml
[✓] ./static/login.html.templatete
[✓] ./static/loginerror.html.templatete
[✓] ./static/js/components/SidebarAndHeader.jsx.templatete
[✓] ./static/js/components/HomePage.jsx.templatete
[✓] ./static/js/components/HeaderContent.jsx.templatete
[✓] ./static/js/components/HoursBelowAirmassPlot.jsx.templatete
[✓] ./static/js/components/Main.jsx.templatete
[✓] ./static/index.html.templatete
[✓] ./baselayer/services/nginx/nginx.conf.templatete
[✓] ./baselayer/services/app/supervisor.conf.templatete
[✓] ./baselayer/services/dask/supervisor.conf.templatete
[✓] ./baselayer/conf/supervisor/supervisor.conf.templatete
|   Config files: baselayer/config.yaml.defaults
|                 config.yaml.defaults
|                 test_config.yaml
| [16:37:16 baselayer] Discovered 12 services
| [16:37:16 baselayer] Enabling 9 services
| 
| [baselayer] Launch app for testing
|   Config files: baselayer/config.yaml.defaults
|                 config.yaml.defaults
|                 test_config.yaml
| ==================================================
| Server at: http://localhost:5000
| Database at: localhost:5432 (skyportal_test)
| Fake OAuth: enabled
| Debug mode: disabled
| ==================================================
|   Config files: baselayer/config.yaml.defaults
|                 config.yaml.defaults
| [16:37:19 test_frontend] Connecting to test database
|   Config files: baselayer/config.yaml.defaults
|                 config.yaml.defaults
|                 test_config.yaml
| [16:37:20 test_frontend] Clearing test database...
| Dropping tables on database skyportal_test
| Creating tables on database skyportal_test
| Refreshed tables: acls, roles, role_acls, users, user_acls, tokens, token_acls, user_roles, cronjobruns, usersocialauths, nonces, associations, codes, partials
| 
| [16:37:21 test_frontend] Waiting for server to appear at http://localhost:5000...
| 
| Welcome to SkyPortal v0.9.dev0+git20221214.51c34650 (https://skyportal.io)
| 
| Checking system dependencies:
[✓] nginx >= 1.7.7                  [  1.18.0]
[✓] psql >= 12.0.0                  [   12.12]
[✓] npm >= 8.3.2.2                  [  8.19.2]
[✓] node >= 16.14.0.0               [ 16.18.1]
[✓] python >= 3.8.8                 [  3.8.15]
| 
[✓] Baselayer installed inside of apppp
| --------------------
[✓] Verifying Python package dependencieses
[✓] Silently executing: baselayer/tools/check_js_deps.shsh
| [16:37:53 baselayer] Compiling configuration templates
|   Config files: baselayer/config.yaml.defaults
|                 config.yaml.defaults
|                 test_config.yaml
[✓] ./static/login.html.templatete
[✓] ./static/loginerror.html.templatete
[✓] ./static/js/components/SidebarAndHeader.jsx.templatete
[✓] ./static/js/components/HomePage.jsx.templatete
[✓] ./static/js/components/HeaderContent.jsx.templatete
[✓] ./static/js/components/HoursBelowAirmassPlot.jsx.templatete
[✓] ./static/js/components/Main.jsx.templatete
[✓] ./static/index.html.templatete
[✓] ./baselayer/services/nginx/nginx.conf.templatete
[✓] ./baselayer/services/app/supervisor.conf.templatete
[✓] ./baselayer/services/dask/supervisor.conf.templatete
[✓] ./baselayer/conf/supervisor/supervisor.conf.templatete
|   Config files: baselayer/config.yaml.defaults
|                 config.yaml.defaults
|                 test_config.yaml
| [16:37:57 baselayer] Discovered 12 services
| [16:37:57 baselayer] Enabling 9 services
| 
| [baselayer] Launch app for testing
|   Config files: baselayer/config.yaml.defaults
|                 config.yaml.defaults
|                 test_config.yaml
| ==================================================
| Server at: http://localhost:5000
| Database at: localhost:5432 (skyportal_test)
| Fake OAuth: enabled
| Debug mode: disabled
| ==================================================
| [17:08:13 test_frontend] Could not launch server processes; terminating
| Javascript bundle not found, did Webpack fail?
| [17:08:13 test_frontend] Terminating supervisord...
| [17:08:13 test_frontend] Failed to launch pytest
[API & frontend/test-3]   ❌  Failure - Main Run front-end tests part 2
[API & frontend/test-3] exitcode '255': failure
[API & frontend/test-3] ⭐ Run Post Checkout main
[API & frontend/test-3]   🐳  docker exec cmd=[node /var/run/act/actions/actions-checkout@v3/dist/index.js] user= workdir=
[API & frontend/test-3]   💬  ::debug::Getting git version
| [command]/usr/bin/git version
| git version 2.38.1
[API & frontend/test-3]   💬  ::debug::Set git useragent to: git/2.38.1 (github-actions-checkout)
[API & frontend/test-3]   ⚙  ***
| Temporarily overriding HOME='/tmp/17e55ec7-5053-4d5b-862c-8e3ac313e8c1' before making global git config changes
| Adding repository directory to the temporary git global config as a safe directory
| [command]/usr/bin/git config --global --add safe.directory /Users/bhealy/skyportal
| [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
| [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
| Entering 'baselayer'
| [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
| [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
| Entering 'baselayer'
[API & frontend/test-3]   💬  ::debug::Unsetting HOME override
[API & frontend/test-3]   ✅  Success - Post Checkout main
[API & frontend/test-3] 🏁  Job failed
| [17:13:46 test_frontend] Could not launch server processes; terminating
| Javascript bundle not found, did Webpack fail?
| [17:13:46 test_frontend] Terminating supervisord...
| [17:13:46 test_frontend] Failed to launch pytest
[API & frontend/test-2]   ❌  Failure - Main Run front-end tests part 1
[API & frontend/test-2] exitcode '255': failure
[API & frontend/test-2] ⭐ Run Post Checkout main
```

**Comment by bfhealy** [comment]
@mcoughlin I could try that, although it looks like the tests are running on multiple containers:

Screen Shot 2022-12-14 at 11 58 12 AM

**Comment by mcoughlin** [comment]
@bfhealy Ah cool. Maybe you can exec into the containers and see if there are any more logs?

**Pull request merged**
