### PR TITLE
WIP: update react-hook-form

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR updates react-hook-form to 7.38.0.

### CODE REVIEW

**Review by guynir42 — APPROVED** [review]

**Comment by mcoughlin** [comment]
@jadalilleboe given your superpowers at this, if it would take you 5 minutes to solve one of the migrations in the form: https://react-hook-form.com/migrate-v6-to-v7/ I suspect I could finish the rest off once I see how it works for how are forms work...

**Comment by jadalilleboe** [comment]
https://stackoverflow.com/a/67186200

**Comment by jadalilleboe** [comment]
```
<TextField
                label="Token name"
             ---   inputRef={register({ required: true })}
            +++    {...register("test", { required: true })}
                name="name"
                error={!!errors.name}
                helperText={errors.name ? "Required" : ""}
```

**Comment by jadalilleboe** [comment]
This is how to fix the register thingy I think, still unclear how to fix props.render is not a function

**Comment by jadalilleboe** [comment]
@mcoughlin omg no way i hacked a fix for the source page look

**Comment by jadalilleboe** [comment]
from 
```
 <Controller
              id="groupSelect"
              name="groupIds"
              labelId="notificationGroupSelectLabel"
              as={Select}
              control={control}
              rules={{
                required: true,
                validate: validateGroups,
              }}
              defaultValue={[]}
              onChange={([event]) => {
                setSelectedGroups(event.target.value);
                return event.target.value;
              }}
              input={<Input id="selectGroupsChip" />}
              renderValue={(selected) => (
                <div className={classes.chips}>
                  {selected.map((value) => (
                    <Chip
                      key={value}
                      label={groupIDToName[value]}
                      className={classes.chip}
                    />
                  ))}
                </div>
              )}
              MenuProps={MenuProps}
              multiple
            >
              {groups.length > 0 &&
                groups.map((group) => (
                  <MenuItem
                    value={group.id}
                    key={group.id.toString()}
                    data-testid={`notificationGroupSelect_${group.id}`}
                    style={getFontStyles(group.id, selectedGroups, theme)}
                  >
                    {group.name}
                  </MenuItem>
                ))}
            </Controller>
```
to
```
<Controller
              id="groupSelect"
              name="groupIds"
              labelId="notificationGroupSelectLabel"
              // as={Select}
              control={control}
              rules={{
                required: true,
                validate: validateGroups,
              }}
              defaultValue={[]}
              onChange={([event]) => {
                setSelectedGroups(event.target.value);
                return event.target.value;
              }}
              input={<Input id="selectGroupsChip" />}
              renderValue={(selected) => (
                <div className={classes.chips}>
                  {selected.map((value) => (
                    <Chip
                      key={value}
                      label={groupIDToName[value]}
                      className={classes.chip}
                    />
                  ))}
                </div>
              )}
              render={() => (
                <Select>
                  {groups.length > 0 &&
                    groups.map((group) => (
                      <MenuItem
                        value={group.id}
                        key={group.id.toString()}
                        data-testid={`notificationGroupSelect_${group.id}`}
                        style={getFontStyles(group.id, selectedGroups, theme)}
                      >
                        {group.name}
                      </MenuItem>
                    ))}
                </Select>
              )}
              MenuProps={MenuProps}
              multiple
            />
```

**Comment by mcoughlin** [comment]
@jadalilleboe Is the main move the <Select> </Select> trick?

**Comment by jadalilleboe** [comment]
yup. delete the as attribute and add a render attribute with the component from the as wrapping around what was in 'main'

**Comment by jadalilleboe** [comment]
at least it worked for the ones in sourcenotification.jsx @mcoughlin

**Comment by mcoughlin** [comment]
@jadalilleboe That did help indeed. static/js/components/FilterCandidateList.jsx is being very tricky if you want to also apply your skills to that one. Also happy to do pair coding tomorrow.

**Pull request merged**
