### PR TITLE
classification test

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR fixes the classification test.

### CODE REVIEW

**Comment by mcoughlin** [comment]
@Theodlz thats fine, it was already there. I was just catching the test sending an empty list and handling it. We could have it error out instead, but it would be a change of behavior. On the plus side, it is only posted to the groups the source is in.

**Comment by Theodlz** [comment]
> @Theodlz thats fine, it was already there. I was just catching the test sending an empty list and handling it. We could have it error out instead, but it would be a change of behavior. On the plus side, it is only posted to the groups the source is in.

Actually I am brining it up because the backend wasn't doing what the backend said before. Couple of people complained that it was posted to the groups of the source and not the public group as advertised, which caused confusion when a classification was saved, then the source saved to more groups and the folks from the new groups would not see them.

I will open another PR before deploy to only post to the public group when not specified (as per the frontend)

**Comment by mcoughlin** [comment]
@Theodlz ok sounds good. Will you add the source to the site-wide group then?

**Comment by Theodlz** [comment]
No! We don't need to add the source to a group to post a classification on it. Classification can just be made public and when accessing a source page (just like you would while scanning) you see it already before saving through source. Also that avoids folks from sending a request to say SEDM when it was already classified  by someone but not share to the public group 3(I saw that happen one or twice)

**Comment by mcoughlin** [comment]
@Theodlz ok sounds good to me!

**Comment by mcoughlin** [comment]
@Theodlz Did you push this change to the classification behavior?

**Pull request merged**
