### PR TITLE
Telescope list

### PR DESCRIPTION
**Pull request by aolrc-vinci**
Hi @mcoughlin,
This is the PR with only the code for displaying the telescope list.
Everything should work.

### CODE REVIEW

**Review by mcoughlin — COMMENTED** [review]
@aolrc-vinci I assume the package.json stuff is not meant to update here. And what exactly does this do? Can you add a screenshot?

**Comment by aolrc-vinci** [comment]
I corrected the changes so now you only have the code relating to displaying the list of telescopes.
This should be what you get when you run the code : 
image

**Comment by mcoughlin** [comment]
@aolrc-vinci And does the list only include the relevant telescopes when you click on one of the dots?

**Comment by Theodlz** [comment]
@mcoughlin I can confirm it does. When you arrive on the page or click on "Telescope List" you see all of them, if you click on a dot you see only the relevant telescopes.

@aolrc-vinci the tests for the telescope page are in the flaky test folder, therefore they do not show a red cross on github if they failed. Please run them locally, and if they work I am happy to merge your PR.

**Comment by Theodlz** [comment]
Oh and one thing you could add in this PR. Right now, the page switches to a mobile version if the screen is too small to display the map + list in a decent ratio (that maps gets too small as its shape is fixed).
Could you either fix that so that the shape of the map fits the space available on the page, or more simply just change `600` to `1200` on line 28 of the `TelescopePage.jsx` component? 

Thanks.

**Comment by aolrc-vinci** [comment]
Thanks to Lydie's help, @ManonFlt and I managed to add the search bar for the telescope. It should be working.
I also fixed the maps ration for mobile.

**Comment by mcoughlin** [comment]
@aolrc-vinci Where does the search bar appear? I don't see it clearly on the page.

**Comment by aolrc-vinci** [comment]
Yes sorry I had forgotten to push some of the changes, it should be fixed now.

**Pull request merged**
