### PR TITLE
Upgrade MUI tables to v5

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR follows https://mui.com/material-ui/guides/migration-v4/ to upgrade mui.

The theme stuff (https://mui.com/material-ui/guides/migration-v4/#theme-structure) needs work.

### CODE REVIEW

**Review by profjsb — COMMENTED** [review]
Seems like a good thing to do here, but remains a work in progress. Perhaps fix the conflicts and see where we're at?

**Comment by mcoughlin** [comment]
@profjsb My guess is that instead of trying to keep rebasing, we should just do this all at once. What do you think?

**Comment by profjsb** [comment]
But we'll want the front end tests passing before merging to main, right?

**Comment by profjsb** [comment]
I'm ok with this if you want to do this today/weekend. We can ask people to get remaining frontend merges in now.

**Comment by mcoughlin** [comment]
@profjsb agreed.

**Comment by mcoughlin** [comment]
@profjsb actually might also be better once the Gaia stuff is gone to differentiate..

**Comment by profjsb** [comment]
We merged the Gaia fixes. Went green on main yesterday

**Comment by mcoughlin** [comment]
@profjsb ah thats a bad sign ;)

**Comment by mcoughlin** [comment]
@jadalilleboe the MUI tables upgrade stuff seems to have broken the Theme, although I am pretty sure it's at least close (https://mui.com/material-ui/customization/how-to-customize/). Do you have time to take a look or give me pointers where I have gone wrong? I know your other stuff is starting (has started) soon!

**Comment by jadalilleboe** [comment]
@mcoughlin All the template files like SidebarAndHeader.jsx.template and HomePage.jsx.template are still using @material-ui/core imports, that would be a problem I think.

**Comment by mcoughlin** [comment]
@jadalilleboe AH yes. And with that, I have managed to make the greatest user experience... of all time.

**Comment by mcoughlin** [comment]
@jadalilleboe I don't think the best part is the missing horizontal scroll bar, but mostly the content hidden behind the side and top bars.

**Comment by jadalilleboe** [comment]
omg

**Comment by jadalilleboe** [comment]
at least it's not all purple anymore lol

**Comment by mcoughlin** [comment]
@jadalilleboe i consider that a loss. Also the interchanging size of the size bar, I think it adds some interest.

**Comment by profjsb** [comment]
@mcoughlin I found a few weird buttons, sliders, and text placement within textboxes.  Happy to merge after these are addressed (or you can decide to make a separate PR for these). LMK!

On User Prefs:
image

image

In dashboard preferences:
image

image

In Candidates:
image

**Comment by mcoughlin** [comment]
@profjsb yeah I suggest we merge and you open an issue with those screenshots and assign me. I think it will be easier as @jadalilleboe noted we should fix up some of the button stuff overall at the same time.

**Review by profjsb — APPROVED** [review]
Apart from a few styling issues I think we're good to go here.

**Pull request merged**
