### PR TITLE
Re-skin info section in CandidateList

### PR DESCRIPTION
**Pull request by dmitryduev**
Proposed re-skin:
- Focus user's attention on 1) object ID that when clicked always opens in a new tab 2) if it's saved 3) if it's classified:
image

That's how it looks like now:
image

### CODE REVIEW

**Review by acrellin — APPROVED** [review]
Looks better to me :+1:

**Review by dannygoldstein — APPROVED** [review]

**Comment by dannygoldstein** [comment]
Looks like lots of candidate failures on CI

**Review by kmshin1397 — APPROVED** [review]
Yeah, I like this - thanks Dima! I think test failures should just be a matter of changing some xpath tags to reflect the changes.

**Review by profjsb — APPROVED** [review]
Looks good to me.

**Comment by dmitryduev** [comment]
Yea, test failures were real, fixed them. Should be mergeable once CI is done with its thing.

**Comment by dmitryduev** [comment]
Failure in `test_source_count_widget` seems unrelated.

**Pull request merged**
