### PR TITLE
DECam instrumental sensitivity

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR adds DECam instrumental sensitivity.

### CODE REVIEW

**Comment by igorandreoni** [comment]
Zeropoints for 30s exposure, airmass=1 (average for all CCDs)
u 26.87
g 28.91
r 29.06
i 28.97
z 28.68
Y 27.57

Hence:
sensitivity_data: {'sdssu': {'limiting_magnitude': 21.6, 'magsys':
'ab', 'exposure_time': 30, 'zeropoint': 26.87,}, 'desg':
{'limiting_magnitude': 23.3, 'magsys':
'ab', 'exposure_time': 30, 'zeropoint': 28.91,}, 'desr':
{'limiting_magnitude': 23.1, 'magsys': 'ab', 'exposure_time': 30,
'zeropoint': 29.06,}, 'desi': {'limiting_magnitude': 22.8, 'magsys':
'ab', 'exposure_time': 30, 'zeropoint': 28.97,}, 'desz':
{'limiting_magnitude': 22.1, 'magsys':
'ab', 'exposure_time': 30, 'zeropoint': 28.68,}, 'desy':
{'limiting_magnitude': 20.9, 'magsys':
'ab', 'exposure_time': 30, 'zeropoint': 27.57,}}

**Comment by mcoughlin** [comment]
@igorandreoni Take another look now?

**Comment by mcoughlin** [comment]
@igorandreoni Can I merge this?

**Comment by mcoughlin** [comment]
@igorandreoni Yeah, this is just about the limiting magnitudes.

**Pull request merged**
