### PR TITLE
Format configuration in YAML format

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Review by mcoughlin — COMMENTED** [review]
@stefanv Are the '' required when doing it like this?

**Comment by stefanv** [comment]
Only for fields that contain special values. I was too lazy to check those two, but I should.

**Comment by mcoughlin** [comment]
@stefanv I downloaded it and removed the '' and it seemed to load ok at least, so hopefully is fine.

**Comment by stefanv** [comment]
Feel free to push to my PR and merge.

**Pull request merged**
