### PR TITLE
Remove old stuff on phot plot

### PR DESCRIPTION
**Pull request by jadalilleboe**
remove old stuff on phot plot, the weird form

### CODE REVIEW

**Comment by mcoughlin** [comment]
@jadalilleboe can you say more about what this does? Is stuff disappearing off the plot?

**Comment by jadalilleboe** [comment]
@mcoughlin Yeah removes this form off the plots
image
It's useless and takes up a lot of space and will be replaced soon so might as well remove it I think.

**Comment by jadalilleboe** [comment]
not sure, thomas has been working on the new photometry plotting preferences i think
I just wanted to get rid of that old one before deployment because of how much space it takes up. and it is not useful on its own without saving stuff to the user's preferences.

**Review by mcoughlin — APPROVED** [review]
Looking forward to the fix!

**Pull request merged**
