### PR TITLE
let other users modify observing run assignments

### PR DESCRIPTION
**Pull request by dannygoldstein**
Fixes https://github.com/fritz-marshal/fritz-beta-feedback/issues/51

### CODE REVIEW

**Review by kmshin1397 — APPROVED** [review]

**Review by dmitryduev — COMMENTED** [review]
LGTM, just one q: do we track who did what, just in case?

**Comment by dannygoldstein** [comment]
@dmitryduev This requires a migration, adding.

**Comment by dannygoldstein** [comment]
Actually, NVM, it does not !

**Comment by dannygoldstein** [comment]
@dmitryduev now tracked.

**Comment by dannygoldstein** [comment]
and tested !

**Comment by dannygoldstein** [comment]
ready for merge. green on travis

**Review by kmshin1397 — APPROVED** [review]

**Review by dmitryduev — APPROVED** [review]
👍

**Pull request merged**
