### PR TITLE
pip 22 breaks our dependencies

### PR DESCRIPTION
**Pull request by mcoughlin**
I think the release of pip 22 broke our dependency installation...

### CODE REVIEW

**Comment by mcoughlin** [comment]
@stefanv Any ideas what to do about this one...?

**Comment by profjsb** [comment]
Are you also getting the dependency failures on your local machine with pip22? I'm totally fine with pinning pip.

**Comment by mcoughlin** [comment]
No I cant get it to fail locally for some reason, but that also seems to be a common issue:
https://github.com/pypa/pip/issues/10851

**Comment by profjsb** [comment]
Looks like the fix is coming out very soon (22.0.2) https://github.com/pypa/pip/commit/347d19063f5deab2fb4b6e83a44be4cf8d15fbf4

**Comment by stefanv** [comment]
We should revert this patch once the new pip is out.

**Pull request merged**
