### PR TITLE
CommentList - Missing associated resource type

### LINKED ISSUE #3953: Shifts test is broken
The `test_shifts` test is not working. 
The failure happens when trying to delete a comment from the frontend. 
The delete button only appears when hovering over the comment. 
There's a command to click that comment but that is not the same as hover. 
I don't know how to solve this but I think this is one of the remaining tests that don't work.

### PR DESCRIPTION
**Pull request by Theodlz**
Fixes #3953

### CODE REVIEW

**Comment by mcoughlin** [comment]
@Theodlz I think resourceType is correct. We want to be adding that into all places where comments are returned.

**Comment by mcoughlin** [comment]
@Theodlz I.e. in the handler.

**Comment by Theodlz** [comment]
Ok! Then we should remove the associatedResourceType that is taken as an argument by the frontend methods.
Let me add that in the handlers then.

**Comment by mcoughlin** [comment]
@Theodlz I am fixing it quick in the WINTER PR because its open ;)

**Comment by Theodlz** [comment]
Ok! Let me know if you need a review on any PRs.

**Pull request closed without merging**
