### PR TITLE
Improve sidebar menu item highlighting logic

### LINKED ISSUE #1683: Bolded sidebar link logic should be based on the current URL rather than the last-clicked sidebar link
Currently the last-clicked sidebar link stays highlighted when the user navigates to new pages:
sidebar_link_bold

### PR DESCRIPTION
**Pull request by acrellin**
Simplifies & improves sidebar link highlighting logic.
Closes #1683 
sidebar_link_bold_better

### CODE REVIEW

**Comment by stefanv** [comment]
What do you think, Ari, is it worth building a lightweight wrapper component that unifies setting bold on click?  It'd be nice not to have to specify that check for every link individually.

**Comment by acrellin** [comment]
> What do you think, Ari, is it worth building a lightweight wrapper component that unifies setting bold on click? It'd be nice not to have to specify that check for every link individually.

We could do that, e.g. add a `SidebarLinkText` component, but we'd still need to pass it the link's route and the current route so it can determine the style, so I don't know that it'd really simplify it at all. Thoughts?

**Comment by stefanv** [comment]
I guess the component can get the current route by itself, so it would just need to receive the component's route.

**Comment by acrellin** [comment]
@stefanv okay, done

**Review by stefanv — APPROVED** [review]

**Comment by acrellin** [comment]
Okay to merge, @stefanv ?

**Pull request merged**
