### PR TITLE
Differentiation between detections and non detections in photometry plots

### PR DESCRIPTION
**Pull request by thomasculino**
Currently, we have photometry plots with only circles as markers. This PR aims to differentiate between detections and non detections as requested in #3122.

Currently we have: 
image

After the changes:
image

and when hovering the tooltip you will see additional details: 
image

### CODE REVIEW

**Review by mcoughlin — COMMENTED** [review]
@thomasculino perfect. Could you also add the same thing to SourceMobile.jsx? I know it's funny to keep track of both of these.

**Review by guynir42 — APPROVED** [review]

**Comment by guynir42** [comment]
Thanks @thomasculino I was just talking to some users who said this was really needed!

**Comment by thomasculino** [comment]
> @thomasculino perfect. Could you also add the same thing to SourceMobile.jsx? I know it's funny to keep track of both of these.

I was working on it but the tooltip displays information when hovered so it does not work on mobile. Should I change the position of the tooltip and make it display additional information when clicked instead of hovered for mobile? @mcoughlin

**Comment by mcoughlin** [comment]
@thomasculino ah if that's easy sure, but great point on the hover. Don't let it stop the PR from going in if it's more than a few minutes for you.

**Comment by thomasculino** [comment]
@mcoughlin Done !

**Comment by mcoughlin** [comment]
@thomasculino thanks for doing that!

**Comment by mcoughlin** [comment]
@thomasculino if you have a few minutes, could you add the same fix to https://github.com/fritz-marshal/fritz/blob/main/extensions/skyportal/static/js/components/SourceDesktop.jsx? We have a copy because of a few extra buttons. I would like to think about how to re-emerge these for extensions of this kind, as it is annoying to keep them each independently up to date. @Theodlz in case you have ideas there. The diff isn't so bad; but there are more buttons.

**Comment by Theodlz** [comment]
Basically the problem to solve here is being able programmatically to do something similar to a git merge right ? So if there are no conflict, its easier for the dev to update a file that has a copy in the extensions, or even completely automatic (but thats not necessarily a good idea, there will always be conflicts at some point and that could be problematic for deployement)

**Comment by Theodlz** [comment]
I have an idea on how to do something that could help. I'll try that

**Comment by Theodlz** [comment]
Here's a quick example on how we could handle that. Git has a command called `git merge-file`. The arguments are: `current-version` `common-ancestor` `other-version`. So here, lets say you created a modified version of the source page on fritz, with skyportal version A. Lets call that SourcePageFritz, and the original one SourcePageOld. Now there is a new version of SkyPortal, B, in which you'll find SourcePageNew (those are examples, in reality all those files have the same names of course, just a different directory). So we have the `current-version  = SourcePageNewSky`, `common-ancestor = SourcePageOld` and `other-version = SourcePageFritz`.

**Comment by mcoughlin** [comment]
@Theodlz really beautiful. Can we plan to discuss on Tuesday maybe?

**Comment by profjsb** [comment]
Can we promote this merge idea to a SkyPortal discussion topic? I'd like to decouple this important idea from the original PR. Also want to pull in @stefanv ?

**Comment by mcoughlin** [comment]
@profjsb of course! @Theodlz might move the discussion to an issue. Definitely will discuss on Tuesday.

**Comment by profjsb** [comment]
Rather than an issue perhaps a back and forth over a Discussion is better? A la https://github.com/skyportal/skyportal/discussions/2638

**Pull request merged**
