### PR TITLE
Add buttons for clearing/adding photometry

### PR DESCRIPTION
**Pull request by jadalilleboe**
https://user-images.githubusercontent.com/82007190/160194147-ea89c997-ff26-41a2-ae8f-5f89e4d3f454.mp4

@mcoughlin Is this what's desired? Adds a button for clearing photometry, add all, and add ZTF only.

### CODE REVIEW

**Comment by mcoughlin** [comment]
@jadalilleboe I like it. Maybe for ZTF, we can add a flag in the config to turn that on or off? What do you think @guynir42 ?

**Comment by guynir42** [comment]
I would be most happy if the "ZTF only" was configurable in a way that lets you choose lists of filters, give them a common name, and have that turn up as buttons.

**Comment by guynir42** [comment]
@jadalilleboe any updates on this?

**Comment by jadalilleboe** [comment]
@guynir42 I looked into what you suggested but I think it would take me a while longer to figure it out. Maybe for now we can merge just the clear photometry and add all photometry buttons and I can work on a different PR for making it configurable

**Comment by guynir42** [comment]
@jadalilleboe yeah that sounds fine.

**Review by guynir42 — APPROVED** [review]

**Comment by mcoughlin** [comment]
Thanks @guynir42. Keeping track of the issue here: https://github.com/skyportal/skyportal/issues/2788

**Pull request merged**
