### PR TITLE
Renewed pull request for Spec lines from forked branch

### PR DESCRIPTION
**Pull request by rjoebruch**
Re initiated the pull request for the spec lines from forked branch as Stefan requested. 
In trying to debug, the "make test" encountered 104 errors/. 
Let me know what to do from there. 
Thank you!

### CODE REVIEW

**Review by dmitryduev — APPROVED** [review]
LGTM! @dannygoldstein wanna merge?

**Comment by dannygoldstein** [comment]
Seems to still be failing CI.

**Comment by dannygoldstein** [comment]
@rjoebruch  - can you provide a citation for the data sources for these lines? also, I noticed that you deleted some of the lines that were in there before (e.g., some of the Si II lines). Can you say a bit about why these lines should be deleted?

**Comment by rjoebruch** [comment]
Hi! 
The lines are form the NIST database. Do you need a specific citation from a paper, or a reference from either Growth/Wiserep? 

Regarding the SiII line which was removed, it can obviously be added back, however this choice arose form discussions with Avishay and Ofer regarding the most used lines for SN classification. 

Let me know if of anymore question

Best! 
--
Rachel

**Comment by acrellin** [comment]
@stefanv @dannygoldstein I see you're still tagged for review here -- any changes you want to see here?

**Review by stefanv — COMMENTED** [review]
Looks good to me; what's up with the Telluric lines?

**Comment by rjoebruch** [comment]
For the tellurics, it was commented out at the end of the edit. Because they are supposedly bands, I was not sure whethere you'd want a forest of concentrated line or just two values (lower and upper bound) and had an option similar to plt.axvspan() for the plotting. 

# Tellurics
# 'Tellurics' : ( np.append(list(np.linspace(6867,6884)), list(np.linspace(7594,7621))), '#99FFFF'     )

**Comment by rjoebruch** [comment]
What is the status of here, is there anything more that I can do?

**Comment by dmitryduev** [comment]
@rjoebruch looks like linting failed and the CI did not run because of that - could you please fix it? Did the pre-commit hook (https://skyportal.io/docs/dev.html#pre-commit-hook) run as expected?

**Comment by dmitryduev** [comment]
CI failure seems unrelated, merging.

**Pull request merged**
