### PR TITLE
Fix permissions on spectroscopy plot 

### PR DESCRIPTION
**Pull request by dannygoldstein**
The spectroscopy bokeh plot was not doing any ACL checking and was showing all spectra associated with an object rather than just the ones that were associated with any of the requesting user's groups. This PR fixes this by adding in an ACL check to the `spectroscopy_plot` function.

### CODE REVIEW

**Review by kmshin1397 — APPROVED** [review]
I noticed that the GET spectrum handler seems to just check that the Obj for the spectrum is accessible to the user and doesn't check the GroupSpectrum records. I think the check here is more correct? Would it make sense to change the GET spectrum handler to use the same ACL check as well?

**Comment by dannygoldstein** [comment]
@kmshin1397 you are absolutely right. that's a critical one - will push up a fix

**Comment by dannygoldstein** [comment]
@kmshin1397 fixed

**Review by kmshin1397 — APPROVED** [review]

**Comment by kmshin1397** [comment]
@dannygoldstein I think some of the test failures may be related - I see some tests timing out while looking for the bokeh plot.

**Comment by dannygoldstein** [comment]
@kmshin1397  nice catch, again, thanks. - hopefully fixed now.

**Comment by dannygoldstein** [comment]
failures unrelated

**Review by dmitryduev — APPROVED** [review]
LGTM!

**Pull request merged**
