### PR TITLE
Fix join b/w Group and Source in SourceHandler

### PR DESCRIPTION
**Pull request by acrellin**
Closes https://github.com/fritz-marshal/fritz/issues/231

### CODE REVIEW

**Review by kmshin1397 — APPROVED** [review]

**Review by dmitryduev — APPROVED** [review]

**Comment by dmitryduev** [comment]
@acrellin `test_post_photometry_all_groups` is failing (in addition to the big post) - have you been seeing this recently?

**Comment by kmshin1397** [comment]
@dmitryduev Where is `test_post_photometry_all_groups` failing?

**Comment by kmshin1397** [comment]
Ah, I see it - will investigate

**Comment by kmshin1397** [comment]
> @acrellin `test_post_photometry_all_groups` is failing (in addition to the big post) - have you been seeing this recently?

This should be fixed by https://github.com/skyportal/skyportal/pull/1872/commits/4145956dc5f5473bc5040f70ebba06731b624cac

**Pull request merged**
