### PR TITLE
Override User.to_dict to not include preferences

### PR DESCRIPTION
**Pull request by acrellin**
The only place `User.preferences` is needed in the response data is in the profile handler, where it's already manually added to the response data

### CODE REVIEW

**Review by dmitryduev — APPROVED** [review]
LGTM!

**Comment by dmitryduev** [comment]
@acrellin Prob need to pin the lates master with 1413 reverted to make CI happy?

**Comment by acrellin** [comment]
> @acrellin Prob need to pin the latest master with 1413 reverted to make CI happy?

This is already based on latest master; sometimes the app takes too long to spin up on CI, and it seems to be working now after restarting the build

**Review by dannygoldstein — APPROVED** [review]

**Comment by dannygoldstein** [comment]
feel free to self merge after successful CI

**Comment by acrellin** [comment]
sole failure (test_problematic_assignment_44) is unrelated.

**Pull request merged**
