### PR TITLE
Annotation delete button

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR adds delete button for annotations and fixes errorbars in periodic plot.

### CODE REVIEW

**Review by guynir42 — COMMENTED** [review]
Code looks good. Is this delete button going to appear for every user or only for admins? Or is the permission check only done in the handler because each user can delete their own annotations? What happens if I try to delete someone else's annotation?

**Comment by mcoughlin** [comment]
@guynir42 Every user. Permissions is done in the handler so if you are an admin you can delete everyone's and the rest is your ownership.

**Comment by guynir42** [comment]
And if you don't have permission you just see an error right?

**Comment by mcoughlin** [comment]
@guynir42 yes

**Review by guynir42 — APPROVED** [review]

**Pull request merged**
