### PR TITLE
date-time in form

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR use strings rather than form (which has funky local time behavior)

### CODE REVIEW

**Review by Theodlz — APPROVED** [review]
Nice. Didn't you mention on zoom that you overwrote some frontend stuff? Just making sure that automated date reset thing that's on the frontend is working still.

Also one thing to keep in mind is that `date-time` rjsf format works poorly if not incorrectly on IE (now edge), safari, and sometimes firefox. For that alone, going back to a proper date time input (at least the one from rjsf and not a custom MUI-based one) will require more work then just fixing the UTC vs local thing.

LGTM

**Comment by Theodlz** [comment]
> Nice. Didn't you mention on zoom that you overwrote some frontend stuff? Just making sure that automated date reset thing that's on the frontend is working still.
> 
> Also one thing to keep in mind is that `date-time` rjsf format works poorly if not incorrectly on IE (now edge), safari, and sometimes firefox. For that alone, going back to a proper date time input (at least the one from rjsf and not a custom MUI-based one) will require more work then just fixing the UTC vs local thing.
> 
> LGTM

They mention it here: [/docs/usage/widgets/, ](https://rjsf-team.github.io/react-jsonschema-form/docs/usage/widgets/), and I definitely had these issues too.

**Comment by mcoughlin** [comment]
Yeah but the code there doesn't seem to work in the case of date-time, so switching it off still makes sense I think.

**Comment by mcoughlin** [comment]
I will put the old behavior back, but we should look into this more.

**Pull request merged**
