### PR TITLE
Specify server.ssl = True in config defaults

### PR DESCRIPTION
**Pull request by acrellin**
Closes https://github.com/skyportal/skyportal/issues/2044

### CODE REVIEW

**Comment by stefanv** [comment]
I think the correct thing to do is to simply set ssl to True in our config.

Sorry, I may have misled you in my quick comments this morning.

**Comment by acrellin** [comment]
@stefanv done

**Comment by acrellin** [comment]
See also https://github.com/fritz-marshal/fritz/pull/293

**Comment by acrellin** [comment]
@stefanv can you take another look here? Thanks

**Comment by stefanv** [comment]
So this will make most default Docker deployments break; we don't have SSL certificates enabled by default.  We could probably some kind of self-signed certificate, but there is more work to make that happen.

**Pull request closed without merging**
