### PR TITLE
Photometry deduplication

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR enables photometry deduplication.

### CODE REVIEW

**Comment by bfhealy** [comment]
@mcoughlin I'm getting the following error raised when I test out this code locally:

```
Uncaught exception GET /api/sources/ZTF23absbqun/photometry?includeOwnerInfo=true&deduplicatePhotometry=true (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='GET', uri='/api/sources/ZTF23absbqun/photometry?includeOwnerInfo=true&deduplicatePhotometry=true', version='HTTP/1.0', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/Users/bhealy/miniforge3/envs/skyportal_env/lib/python3.10/site-packages/tornado/web.py", line 1784, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/bhealy/skyportal/baselayer/app/access.py", line 56, in wrapper
    return tornado.web.authenticated(method)(self, *args, **kwargs)
  File "/Users/bhealy/miniforge3/envs/skyportal_env/lib/python3.10/site-packages/tornado/web.py", line 3290, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/bhealy/skyportal/skyportal/handlers/api/photometry.py", line 1590, in get
    data = phot_data + series_data
TypeError: unsupported operand type(s) for +: 'dict' and 'list'
```

**Comment by mcoughlin** [comment]
@bfhealy please try again.

**Comment by bfhealy** [comment]
@mcoughlin Thanks, that fixed it! I can now download de-duplicated photometry from the table.

**Review by Theodlz — APPROVED** [review]
LGTM

**Pull request merged**
