### PR TITLE
Observability Page

### PR DESCRIPTION
**Pull request by dannygoldstein**
This PR adds a page that dynamically calculates the observability of a target at every site known to SP, then renders the results as a grid of Vega plots showing airmass vs time. 

The plots show the times of nautical and civil twilight, sunrise, sunset, night time, and the current time. 

cc @mansikasliwal

Kapture 2020-10-31 at 22 10 05

### CODE REVIEW

**Comment by dannygoldstein** [comment]
@kmshin1397 failures on 
https://github.com/skyportal/skyportal/runs/1339501277?check_suite_focus=true 
and 
https://github.com/skyportal/skyportal/runs/1339497861?check_suite_focus=true 
are related to https://github.com/cesium-ml/baselayer/pull/175 I believe

**Review by acrellin — APPROVED** [review]

**Comment by profjsb** [comment]
Some strange responsive behavior, partly due to long telescope names. Might also consider scaling the size of the plots responsively (percentage of page) if possible.
Kapture 2020-11-04 at 09 40 59

**Comment by dannygoldstein** [comment]
@profjsb - fixed. Ready for re review.

**Comment by dannygoldstein** [comment]
failures unrelated

**Review by profjsb — APPROVED** [review]
Thanks for fixing.

**Pull request merged**
