### PR TITLE
Slugify usernames

### PR DESCRIPTION
**Pull request by acrellin**
Closes  https://github.com/skyportal/skyportal/issues/883 

Depends on https://github.com/cesium-ml/baselayer/pull/145

### CODE REVIEW

**Review by stefanv — APPROVED** [review]

**Review by profjsb — CHANGES_REQUESTED** [review]
If the user enters a username with a space or non-alpha character (other than -) it will slugify after they make the change, which can be disconcerting. Instead you should have a tooltip saying something like "Username is any combination of letters and dashes, 3-16 characters in length". Then you can do form validation onsubmit (using a regex to check like `/^[a-zA-Z\-]{3,16}$/`).

**Comment by acrellin** [comment]
@profjsb how about just a note saying that all usernames will be slugified, with a blurb about what that means? When the user clicks save they'll immediately see the slugified username when the new profile data is re-fetched. It won't be a surprise to them.

**Comment by acrellin** [comment]
This one still needs a bit of updating in other parts of the app to get working smoothly

**Comment by acrellin** [comment]
@stefanv @profjsb screen capture: 
slugify_username

**Review by profjsb — APPROVED** [review]

**Pull request merged**
