### PR TITLE
Better sources subclasses slider information classifications ( #3398 )

### PR DESCRIPTION
**Pull request by vyom1611**
The subclasses sliders of a classification would only be visible if the value of the parent slider is greater than 0. This has been implemented for all subclasses for any classification. But, on initial render, the change is not in effect. If you click on the slider label and if the value is 0, then the subclasses get hidden, and if you change the slider again, subclasses come back. But you still need to click the label on 0 for every classification for the first time. Is there any fix for the initial render?

### CODE REVIEW

**Comment by jadalilleboe** [comment]
Hi Vyom, adding this condition seemed to have the intended effect:
`classification.class in formState[selectedTaxonomy.id]`
so then the whole condition would be
```
{classification.class in formState[selectedTaxonomy.id] && formState[selectedTaxonomy.id][classification.class]
              ?.probability !== 0 &&
              renderSliders(
                classification.subclasses,
                depth + 1,
                [classification.class].concat(path)
              )}
```
Although I did find some weird behavior, if I change a classification to have a non-zero probability, submit the form, and then reload the page, the probability is saved like normal. But if I change it back to 0 and submit the form, it is not updated correctly after reloading the page. i.e. if I change Galactic Nuclei to have 0.25 probability and then try to change it back to 0, it stays at 0.25. Is that a bug or is it supposed to be like that @mcoughlin ?

**Comment by mcoughlin** [comment]
@jadalilleboe that sounds like a bug to me.

**Comment by jadalilleboe** [comment]
ok, I will open a new issue.

**Comment by vyom1611** [comment]
Hey @jadalilleboe, can you please tell me which line number do I need to add the above condition, in file MultipleClassificationsForm.jsx?

**Comment by jadalilleboe** [comment]
@vyom1611 The same lines where you added the probability check, check if the key exists as well. Let me know if that helps

**Comment by vyom1611** [comment]
Yes, this fix seems to work!

**Review by jadalilleboe — APPROVED** [review]

**Pull request merged**
