### PR TITLE
Fixing Galaxy page issue using useEffect (issue reference #3325)

### PR DESCRIPTION
**Pull request by vyom1611**
The Galaxy page on initialization showed more galaxies at once than it should, but on changing the page, it was fixed. The issue only occurred at init, so I used a useEffect hook to change the page when it loads to page 1. Based on issue #3325.

### CODE REVIEW

**Comment by mcoughlin** [comment]
Thanks @vyom1611. Could you please use the linter:

pre-commit install
pre-commit run --files static/js/components/GalaxyPage.jsx

and then recommit to fix the linting issue?

**Comment by vyom1611** [comment]
Hey Michael, just using those commands in the terminal does not do anything. Is there anything else I should install?

**Comment by mcoughlin** [comment]
@vyom1611 You can see where it is failing here: https://github.com/skyportal/skyportal/runs/8276632758?check_suite_focus=true#step:13:66

usually the pre-commit then complains about a file.

**Review by guynir42 — APPROVED** [review]
LGTM.

**Pull request merged**
