### PR TITLE
Allow filtering of observability page via user preferences

### PR DESCRIPTION
**Pull request by kmshin1397**
Partly addresses https://github.com/fritz-marshal/fritz-beta-feedback/issues/61

observability

@dmitryduev Part of that issue was also a request for `the "hours over airmass 2.5" plot` from the GROWTH marshal. If you could point me to where the code for that is, I can try to port it over to SkyPortal as well.

### CODE REVIEW

**Review by acrellin — APPROVED** [review]
Looks great, thanks @kmshin1397 !

**Comment by stefanv** [comment]
Is there a way to clear that preference, or to select all telescopes again?

**Review by dmitryduev — COMMENTED** [review]
Looks great! I have the same question as @stefanv and would also like to request adding some text to the observability page reminding the user of their selection, e.g. "Displaying observability plots for ... You can edit your preferences on the Profile page." or something.

**Comment by stefanv** [comment]
Or have the preference adjustable on that page?

**Comment by stefanv** [comment]
That looks great!

**Review by dmitryduev — APPROVED** [review]
Looks really nice, will merge once the CI has finished. Thanks @kmshin1397!

**Pull request merged**
