### PR TITLE
Use optional chaining when attempting to map JS arrays

### PR DESCRIPTION
**Pull request by acrellin**
This patch employs optional chaining (`?.map`) when attempting to
map JavaScript arrays to avoid crashing in the event that the variable
in question is null or undefined.

### CODE REVIEW

**Comment by stefanv** [comment]
It would be nice to only use these when necessary, but that would take forever to find.  So :+1:

**Review by dmitryduev — APPROVED** [review]
👍🏻 feel free to self-merge once green(ish)!

**Comment by acrellin** [comment]
> It would be nice to only use these when necessary, but that would take forever to find. So +1

Yes, agreed. I did a quick skim of each use case and ended up skipping those where the variable in question would obviously never be `null`. Those that weren't immediately obvious I just went ahead and added the `?` for extra security, even though some of those are unnecessary.

**Comment by acrellin** [comment]
6 green check marks ✅  -- merging

**Pull request merged**
