### PR TITLE
Disable classification shortcuts

### PR DESCRIPTION
**Pull request by jadalilleboe**
disable classification shortcuts added in #2972 until the other buttons on the scanning page are added

### CODE REVIEW

**Comment by mcoughlin** [comment]
@jadalilleboe But this short cut still works right? It just doesn't enable setting classifications?

**Comment by jadalilleboe** [comment]
Yes. So we should disable until it can also set classifications? I guess I wouldn't want users to start using it yet

**Comment by mcoughlin** [comment]
@jadalilleboe I think what's there is still useful, but up to you!

**Review by mcoughlin — APPROVED** [review]
@jadalilleboe Merge on green.

**Pull request merged**
