### PR TITLE
Implement Telescope and Instrument API

### PR DESCRIPTION
**Pull request by acrellin**
Closes https://github.com/skyportal/skyportal/issues/243

### CODE REVIEW

**Comment by profjsb** [comment]
How is the permissioning handled for POST/GET with respect to groups? That is, can anybody with write permission on the DB create a new telescope/instrument? And can they see other people's telescopes/instruments?

**Comment by stefanv** [comment]
@profjsb Currently, instruments are accessible by all.  Should these be tied to a group?

**Comment by profjsb** [comment]
> @profjsb Currently, instruments are accessible by all. Should these be tied to a group?

I think so -- it would be a mild form of IP leakage if one (rival) group could know what instruments the other group is using to observe. The default could be that everyone belongs to a "global" group and that their write/read permissions apply to "global" as well as any specific group(s) they are in. But this would still need to enforce the per-group permissioning logic discussed above.

**Comment by acrellin** [comment]
We're doing a big API security check/overhaul soon - shall we include any changes to the telescope permissions there so we can get this in?

**Pull request merged**
