### PR TITLE
Routing changes on the shift page

### PR DESCRIPTION
**Pull request by thomasculino**
This PR aims to solve a problem we had on the shift page. Currently, using the routing (i.e /shifts/<shift_id>) gets you to the shift page and automatically opens the calendar on the right week and displays the shift management menu, comments and summary of the shift which id has been passed in the route. However, if you already had selected a shift (which is stored as the current shift in the redux store), this does not work.

This PR adresses that issue.

### CODE REVIEW

**Review by mcoughlin — COMMENTED** [review]
@thomasculino If there are actually no shifts, should we have some kind of statement "No shifts available" or similar? Or maybe this is just sufficient. up to you

**Comment by Theodlz** [comment]
> @thomasculino If there are actually no shifts, should we have some kind of statement "No shifts available" or similar? Or maybe this is just sufficient. up to you

Done :heavy_check_mark:

**Review by mcoughlin — APPROVED** [review]
LGTM

**Comment by mcoughlin** [comment]
@Theodlz Please review and merge if comfortable.

**Review by Theodlz — APPROVED** [review]
LGTM.

**Pull request merged**
