### PR TITLE
Add optional plugins for the source and candidate page

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR adds "plugins" for the source and candidate page to simplify extras for those pages (like in extensions).

### CODE REVIEW

**Comment by stefanv** [comment]
How will these plugins we provided?

**Comment by mcoughlin** [comment]
@stefanv As right now our extensions make files of the same name that are copied over, @guynir42 suggested this model where we do the same (but instead of having the whole file copied, just a "plugin" part).

**Review by guynir42 — APPROVED** [review]
Perfect, thanks!

**Comment by stefanv** [comment]
Here are some other ideas you can play around with:

1. As we do with our messagehandlers, you add a Javascript method that a plugin can call to register itself.
2. Copy a *folder* of plugins, and to then use our templating to iterate over the files in the plugin folder and inject them one by one.  This will make the plugins easier to maintain.

**Pull request merged**
