### PR TITLE
Consistent colors for vega photometry plots

### PR DESCRIPTION
**Pull request by scizen9**
Here is an initial try, but it only parses ztf filters.  I have to work on a way to parse all the filters.

### CODE REVIEW

**Comment by scizen9** [comment]
Here's what it does so far:  
image

**Comment by scizen9** [comment]
Attempting to address [Issue #57](https://github.com/fritz-marshal/fritz-beta-feedback/issues/57) and [Issue #681](https://github.com/skyportal/skyportal/issues/681).

**Comment by acrellin** [comment]
@scizen9 What's the status here?

**Comment by dmitryduev** [comment]
@scizen9 any updates here? 

You may want to use the same logic I used [here](https://github.com/fritz-marshal/fritz/blob/master/extensions/skyportal/static/js/components/CentroidPlot.jsx#L338) for Centroid plots.

**Comment by acrellin** [comment]
@scizen9 Any updates here? According to Dima's comment above, this is currently doable. Thanks!

**Comment by acrellin** [comment]
@scizen9 Any updates here?

**Comment by profjsb** [comment]
@scizen9 please followup with Vega developers...

**Comment by dmitryduev** [comment]
@profjsb no need to do that -- see my comment above (I figured out what needs to be done in an older pr).

**Comment by mcoughlin** [comment]
Closing in favor of https://github.com/skyportal/skyportal/pull/2734.

**Pull request closed without merging**
