### PR TITLE
Shift user permissions

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR lowers the permissions threshold for signing up for shifts.

### CODE REVIEW

**Review by Theodlz — CHANGES_REQUESTED** [review]
Hi @mcoughlin, this looks good to me. However as we discussed there is a clear performance issue when you have more than lets say 50 shifts, as there is no pagination right now.

I'm happy to merge this PR, but only if we remove the hydration in action.js until we have a PR addressing the pagination issue, as all users might be affected otherwise.

**Comment by mcoughlin** [comment]
@Theodlz I dont see the shift stuff in the actions.

**Comment by Theodlz** [comment]
Ah! I might have removed it in the past for similar reasons... my bad.

**Review by Theodlz — APPROVED** [review]

**Comment by Theodlz** [comment]
LGTM @mcoughlin

**Pull request merged**
