### PR TITLE
Return new source info in source update response

### PR DESCRIPTION
**Pull request by acrellin**

### CODE REVIEW

**Comment by stefanv** [comment]
I just read [this SO answer](https://stackoverflow.com/questions/797834/should-a-restful-put-operation-return-something) and feel quite conflicted.  What do you think after reading that?

**Comment by stefanv** [comment]
Just learned that we are using the wrong HTTP status codes for successful POST as well :)

**Comment by stefanv** [comment]
For our use case, perhaps we should rather *not* include the modified body.  In Danny's application, we can then untoggle the button if the request comes back a failure.  That seems even simpler to implement for now.  Sorry for going back and forth on this.

**Comment by acrellin** [comment]
@stefanv I just looked over that standard, and we definitely do not follow it throughout the application, both in terms of status codes and response content -- e.g. we return the new record's ID in the response body for POST requests. But if you want to move towards complying with that spec, sure, I'll scrap this and we can take care Danny's update score issue with the other approach we discussed.

**Comment by acrellin** [comment]
@stefanv actually, if we want to conform with that standard, we'll have to do away with returning the SkyPortal version in the response body as we currently do for all requests.

**Comment by acrellin** [comment]
@stefanv actually, after a more careful reading, this standard just specifies the status codes that should be used, but doesn't say that the body should be empty.

**Comment by acrellin** [comment]
@stefanv ah, never mind - this doc does indeed say a PUT response should have no body: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT

**Comment by acrellin** [comment]
(a successful POST response should have a body, however)

**Comment by acrellin** [comment]
@stefanv looks like we should actually be using PATCH instead of PUT for our update handlers, in which case the response SHOULD have a body :)

**Comment by acrellin** [comment]
Will update the API to use PATCH where appropriate, and will return the updated record in those responses. See upcoming separate PR.

**Pull request closed without merging**
