### PR TITLE
Basic event page display

### PR DESCRIPTION
**Pull request by mcoughlin**
Playing around with a sample event page display.

### CODE REVIEW

**Comment by mcoughlin** [comment]
Jun-26-2021 18-04-02

**Comment by mcoughlin** [comment]
@acrellin @kmshin1397 This is blocked by #2082, but can be looked at for initial feedback as you have time.

**Review by acrellin — APPROVED** [review]
I'm not familiar with any of the d3-related stuff here so can't comment on that, but looks good to me :+1:

**Comment by mcoughlin** [comment]
@acrellin could you help me understand what I am doing wrong with the package stuff? it is in package.json but lint don't like it. Also my page making skillz aren't great if you have ideas how to make things fit nicely on the page as you do for your other pages.

**Comment by acrellin** [comment]
I'll see if I can reproduce the eslint error locally

**Comment by mcoughlin** [comment]
@acrellin did you have any luck understanding the linting here?

**Comment by acrellin** [comment]
Now the app fails to spin up in what appears to be a new, unrelated issue, which I can't reproduce locally, either 🤔

**Comment by acrellin** [comment]
The current issue appears to be occurring on other PRs as well, so assuming unrelated

**Review by kmshin1397 — COMMENTED** [review]
@mcoughlin Good to finally see this green! I'm sure there's plenty of improvements and prettifying to do here eventually, but this looks like a good baseline to work off of :) The one thing I think is missing is to update the `config.yaml.defaults` to add a route to `GcnEventPage` in the `app.routes` section so that we actually have a way of getting to this page and referring to it in the follow-up PRs.

**Comment by mcoughlin** [comment]
Thanks @kmshin1397. As long as you are cool with turning on that functionality, I am!

**Review by kmshin1397 — APPROVED** [review]

**Comment by kmshin1397** [comment]
> Thanks @kmshin1397. As long as you are cool with turning on that functionality, I am!

No harm in putting it in the default configs - we can always take it out of the deployed configs if we feel like it's not ready :) But yeah I think once the Events page PR goes in I'm fine turning the service on and enabling all the pages.

**Pull request merged**
