### PR TITLE
GCN event getter

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR tries to refactor the GCN event getter to make it useful for the crossmatch page. Something about the state is funny.. I wonder if you can take a quick look @Theodlz?

### CODE REVIEW

**Comment by Theodlz** [comment]
On it @mcoughlin

**Comment by mcoughlin** [comment]
@Theodlz The second GCN doesn't load in for me at least.

**Comment by Theodlz** [comment]
Ohh ok I see, yeah there were two bugs then and I fixed the other one 😅. Let me have another look.

**Comment by Theodlz** [comment]
What about now? Works just fine for me on my end.

**Comment by mcoughlin** [comment]
@Theodlz Magic. Can we review and get it in?

**Review by Theodlz — APPROVED** [review]
LGTM

**Comment by Theodlz** [comment]
Oh @mcoughlin, we will need a second PR to add this getter to the skymap queue submission btw.

**Comment by mcoughlin** [comment]
@Theodlz If you can do it in a follow-on PR, then great. Let's get this in so it works for deploy tomorrow.

**Pull request merged**
