### PR TITLE
[Analysis Epic] Individual analysis page

### PR DESCRIPTION
**Pull request by profjsb**
Add a linkable page for individual analyses on a given object. Accessed via `/source/source_name/analysis/analysis_id`.

Kapture 2022-08-03 at 19 40 15

### CODE REVIEW

**Review by guynir42 — COMMENTED** [review]
The code seems fine. I am still unable to send an analysis successfully to see the results page.

**Comment by mcoughlin** [comment]
@guynir42 i always run the service in another terminal explicitly.

**Review by mcoughlin — APPROVED** [review]
@profjsb looks great to me!

**Comment by guynir42** [comment]
@mcoughlin That makes a lot of sense. Is there a documentation somewhere describing how to do that, in testing and in production where it should be managed by supervisord or something like that?

**Comment by mcoughlin** [comment]
@guynir42 i think for now we don't want the demo sn fitter running in production as it doesn't run the full MCMC load. When we get NMMA finished and merged we definitely will though.

I think the docs are ok, although for this particular case it is just running python on app.py in the sn service folder

**Comment by guynir42** [comment]
Where in the docs can I find this?

**Comment by mcoughlin** [comment]
@guynir42 oh that bad is just knowledge from trying it out, but I don't think we need to highlight how to run that service for folks.

**Comment by profjsb** [comment]
@guynir42 The demo fitting microservice should just work after `make load_demo_data` -- it also works in testing. You should have in your `config.yaml`:

```yaml
analysis_services:
  analysis_folder: analysis_data
  sn_analysis_service:
    port: 6801
```

(it's in `config.yaml.defaults`).

**Comment by guynir42** [comment]
OK I managed to get it running as @mcoughlin suggested. It did not automatically start the processes when I used `load_demo_data`.

**Comment by guynir42** [comment]
I can now see the analysis results page which is nice. I can't scroll down to see the entire PDF:
Screenshot from 2022-08-03 14-40-28

**Comment by guynir42** [comment]
Also I have a few suggestions on the display of parameters:
- The `param_names` and `parameters` can just be merged into dictionary with name: value (like for `errors`). 
- The data mask can be converted to an array of `int` to be easier to read. 
- Maybe display a chi2/dof in addition to the two separate values?

**Comment by guynir42** [comment]
On the source page I have two issues that may belong in a separate PR: 
1) The analysis results do not show up when done, only after I refresh the page.
2) The column called "Analysis service" shows number 1 for the demo analysis (I assume it's the ID). Should display the name of the analysis service instead.

**Comment by profjsb** [comment]
> Also I have a few suggestions on the display of parameters:
> 
>     * The `param_names` and `parameters` can just be merged into dictionary with name: value (like for `errors`).
> 
>     * The data mask can be converted to an array of `int` to be easier to read.
> 
>     * Maybe display a chi2/dof in addition to the two separate values?

All of these are not the responsibility of the frontend (or even SkyPortal) but instead are the free-form results from the analysis service. In this case we're just using the results that are generated by `sncosmo`. I think it's beyond the scope for us to try to reformat and rename in a way that's generic to all analyses possible.

**Comment by profjsb** [comment]
> On the source page I have two issues that may belong in a separate PR:
> 
>     1. The analysis results do not show up when done, only after I refresh the page.
> 

Yes, I noted this shortcoming in the original PR for that list/form. Should be changed elsewhere.

>     2. The column called "Analysis service" shows number 1 for the demo analysis (I assume it's the ID). Should display the name of the analysis service instead.

The name and description are given with a mouseover. We show id numbers elsewhere in the app (like in the Assignments, we should Run Id).

**Comment by profjsb** [comment]
> I can now see the analysis results page which is nice. I can't scroll down to see the entire PDF: Screenshot from 2022-08-03 14-40-28

Will need some help on this -- it works on my browser.

**Comment by guynir42** [comment]
I still thing the table should show the name of the analysis. I don't think the ID means much to the user and it is not a big effort on our end to show the name.

**Comment by mcoughlin** [comment]
@profjsb @guynir42 What do we need to get this in?

**Review by guynir42 — APPROVED** [review]
Looks good. I will look into the PDFs not scrolling, and we can deal with that in a separate PR.

**Comment by mcoughlin** [comment]
@profjsb Can we merge?

**Pull request merged**
