### PR TITLE
Use driver.wait_for_xpath_missing in front-end tests

### PR DESCRIPTION
**Pull request by acrellin**

### CODE REVIEW

**Comment by stefanv** [comment]
Does this wait until the element disappears then?

**Comment by acrellin** [comment]
@stefanv by default, this checks every 0.5 seconds until the specified element no longer exists, up to (configurable) 5 seconds. But if the element is already gone when this is called, it returns immediately.

**Comment by acrellin** [comment]
https://seleniumhq.github.io/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.wait.html

**Comment by stefanv** [comment]
The naming is just awkward.  Would something like `wait_for_xpath_to_disappear`, e.g., not read more logically?

**Comment by acrellin** [comment]
Sure, I'll change it to that!

**Comment by stefanv** [comment]
We may have to check that we don't break Cesium as well.  Thanks!

**Comment by acrellin** [comment]
Done! I'll update cesium as well.

**Comment by acrellin** [comment]
@stefanv turns out we were never using that in `cesium_web`, so no issues there

**Pull request merged**
