### PR TITLE
Limit group name in save candidate button to 15 chars

### PR DESCRIPTION
**Pull request by acrellin**
Closes https://github.com/skyportal/skyportal/issues/859

image

### CODE REVIEW

**Review by dmitryduev — APPROVED** [review]
Thanks, @acrellin! I checked the group names in the seed config -- many are quite long, so please let's do 15 chars :)

**Comment by dmitryduev** [comment]
Failure on Travis is unrelated, should probably mark that test xfail.

**Comment by acrellin** [comment]
@dmitryduev Done and pushed

**Comment by dmitryduev** [comment]
👍 thanks, will merge once CI run has finished.

**Pull request merged**
