### PR TITLE
Source page spinner

### LINKED ISSUE #1911: Display spinner in source tables while data is loading
...otherwise at first it looks like there's nothing there; the lag seems too long to not bother.

### PR DESCRIPTION
**Pull request by guynir42**
We want to have a spinner running when there is a filtering/sorting request, so it doesn't look like nothing changes when those changes are applied. 

Closes #1911

### CODE REVIEW

**Comment by guynir42** [comment]
@acrellin I need some help with this. 
I found a good place to put `setQueryInProgress(true)` but I don't know where to put the `false` part. 
Right now the spinner appears when the filter is selected but it doesn't disappear, even when the `FETCH_SOURCES_OK` comes back.

**Comment by acrellin** [comment]
@guynir42 I'd use a `useEffect` hook which sets the value to `false` when `sources` state is updated and is non-null/not-empty

**Comment by guynir42** [comment]
> @guynir42 I'd use a `useEffect` hook which sets the value to `false` when `sources` state is updated and is non-null/not-empty

@acrellin but the `SourceTable` doesn't access the state directly, it can use either the "latest" or "groupSources" depending on where the component is used.

**Comment by acrellin** [comment]
@guynir42 `sources` is passed in as a prop -- the `useEffect` should watch for changes in that variable

**Review by acrellin — APPROVED** [review]

**Comment by acrellin** [comment]
@guynir42 can you link to the related issue using the keyword "Closes" so that it'll be closed when this is merged?

**Comment by guynir42** [comment]
Closes #1911

**Comment by acrellin** [comment]
@guynir42 it actually has to be in the PR description in order to work, sorry I should've mentioned that

**Comment by acrellin** [comment]
(I just updated it)

**Comment by acrellin** [comment]
@guynir42 the spinner appears centered in the page -- can you update its containing div/grid's css to make it left-justified? it looks odd centered in the page

**Comment by guynir42** [comment]
I moved the spinner and fixed some tests, I think it is go for second review @acrellin @kmshin1397

**Review by acrellin — APPROVED** [review]

**Comment by guynir42** [comment]
@kmshin1397 if you have time to review and merge this one, it's a short one...

**Review by kmshin1397 — APPROVED** [review]

**Pull request merged**
