### PR TITLE
GCN Event in confirmed sources plot

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR notes GCN Event in confirmed sources plot. (closes https://github.com/skyportal/skyportal/issues/4226)

### CODE REVIEW

**Comment by Theodlz** [comment]
Hi @mcoughlin. This works just fine. Just not sure people want to show a line for the GCN trigger on photometry plots only if the source has been highlighted/confirmed. I might have misunderstood the user request (i think it was Dan?), but I believe this was a thing they should be able to see on sources without having to manually query for the sources and highlight interesting ones. I mean if they queried it and got it, that already means it was detected within X days after the event, so I'm not sure I see why they need that on the plot then.

**Comment by mcoughlin** [comment]
@Theodlz I mean it's always nice to see the GRB time relative to the first detection. So I disagree.

**Comment by Theodlz** [comment]
Ok that makes sense. Just want to know if we expect people to actively confirm/highlight a source before being able to see that line/marker. Btw little suggestion but I would add a dotted line with a low opacity, as the current implementation isn't that easy to read. Probably can just reuse the code for the detections but use the `dash` (or dashed) method of bokeh.

**Comment by mcoughlin** [comment]
@Theodlz Can you give the syntax or just push it?

**Comment by Theodlz** [comment]
@mcoughlin talked with Robert and we agreed on what to do (for which sources to show, and what to show). So its for highlighted (old confirm) and ambiguous (have a row but not confirmed or rejected), and we show a dotted line + the G marker.

**Comment by mcoughlin** [comment]
@Theodlz Ok.

**Pull request merged**
