### PR TITLE
update Vega vs AB in photometry table

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR improves handling of columns / Vega vs AB in photometry table.

### CODE REVIEW

**Comment by Theodlz** [comment]
@mcoughlin can you tell me a little more about what this does exactly? I mean I understand the code, but not sure why some of it is there (like sending the magsys from server to client, and the thing with the `openColumns`)?

**Comment by mcoughlin** [comment]
Columns would reset after every interaction. And Magsys was not respected when editing

**Review by Theodlz — APPROVED** [review]
LGTM boss

**Comment by Theodlz** [comment]
@mcoughlin looks like a test is failing with these changes: `skyportal/tests/frontend/sources_and_observingruns_etc/test_sources.py:783 in test_show_photometry_table`

**Pull request merged**
