### PR TITLE
ObservingRun model [ch823] [ch824]

### PR DESCRIPTION
**Pull request by dannygoldstein**
Adds two database models: `ObservingRun`, which represents a single, non-robotic follow-up run with a PI, and `Assignment`, which is effectively a join table between `ObservingRun` and `Source` that keeps track of Source assignments to the `ObservingRun`.

### CODE REVIEW

**Comment by dannygoldstein** [comment]
[ch823]

**Comment by dannygoldstein** [comment]
[ch824]

**Comment by acrellin** [comment]
@dannygoldstein any overlap between this and https://github.com/skyportal/skyportal/pull/387, or are followups and observing runs distinct concepts?

**Comment by dannygoldstein** [comment]
There's overlap between the `FollowupRequest` of #387 and the `Assignment` of this PR. In the current (GROWTH) marshal these are separate entities: `FollowupRequest` as currently implemented would be mainly for robotic facilities that can be triggered remotely, whereas `Assignment` would be for classical nights where a human is actually required to make decisions about what will get observed and in what order. But it is worth considering whether `Assignment` and `FollowupRequest` should be merged together on the Skyportal backend as they represent very similar things.

**Comment by acrellin** [comment]
> There's overlap between the `FollowupRequest` of #387 and the `Assignment` of this PR. In the current (GROWTH) marshal these are separate entities: `FollowupRequest` as currently implemented would be for robotic facilities that can be triggered remotely, whereas `Assignment` would be for classical nights where a human is actually required to make decisions about what will get observed and in what order. But it is worth considering whether `Assignment` and `FollowupRequest` should be merged together on the Skyportal backend as they represent very similar things.

@stefanv @profjsb thoughts on combining `FollowupRequest` and `Assignment` in SkyPortal? As @dannygoldstein noted, in the current marshal they represent two slightly different things (robotic vs manual observations).

**Comment by acrellin** [comment]
@dannygoldstein the the followup requests PR merged, I'm happy to work with you on extending that to encapsulate any manual observation concepts from this PR.

**Comment by dannygoldstein** [comment]
closed in favor of a future PR that will be based off #387

**Pull request closed without merging**
