### PR TITLE
Fix 404s generated by invalid fetches to Gravatar

### PR DESCRIPTION
**Pull request by stefanv**
Now, fall back to a transparent image.

Use CSS to add user initials underneath the image.  If a non-blank image is
fetched, it covers the user initials.

### CODE REVIEW

**Comment by stefanv** [comment]
Failures:

- (GA) skyportal/tests/frontend/test_newsfeed.py::test_news_feed_prefs_widget
- (Travis-CI) test_add_new_group

**Comment by stefanv** [comment]
Requires a tiny patch to baselayer as well to change Gravatar URL to:

```
        return f'https://secure.gravatar.com/avatar/{digest}?d=blank'
```

**Comment by stefanv** [comment]
```patch
+        # return a transparent png if not found on gravatar
+        return f'https://secure.gravatar.com/avatar/{digest}?d=blank'
```

**Review by acrellin — APPROVED** [review]

**Comment by profjsb** [comment]
There's a phantom letter that shows up in white: 
image

**Comment by stefanv** [comment]
I don't see this phantom letter.  Could you please:

- shift-reload the page to ensure that you have the latest JavaScript and
- apply the one-line patch to baselayer mentioned above.

**Comment by profjsb** [comment]
Yes, the baselayer change fixed this issue. Perhaps you should commit that to baselayer master then pin that commit in this PR.

**Review by profjsb — APPROVED** [review]
Great. Approved assuming the baselayer pin (as in comments).

**Pull request merged**
