### PR TITLE
Add an endpoint piechart

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR adds a piechart for the endpoints too.

### CODE REVIEW

**Comment by stefanv** [comment]
I would avoid hardcoding endpoints and give the script a more descriptive name.

**Comment by mcoughlin** [comment]
@stefanv What is the proper way to get endpoints?

**Comment by stefanv** [comment]
I don't see why you need them, you can just parse them out of the log line. But if you really need them you can get them from the openapi spec JSON.

**Comment by stefanv** [comment]
You mean like this?

```
In [4]: import urllib

In [5]: urllib.parse.urlparse('/api/foo?x=3&foo=3')
Out[5]: ParseResult(scheme='', netloc='', path='/api/foo', params='', query='x=3&foo=3', fragment='')
```

**Comment by mcoughlin** [comment]
@stefanv Ah. Are you thinking of just a standard loop here over the frame?

**Comment by stefanv** [comment]
Yes, exactly. Pandas has something for that, `apply` maybe?

**Comment by mcoughlin** [comment]
@stefanv I think a loop is maybe easiest after all.

**Review by guynir42 — APPROVED** [review]

**Pull request merged**
