### PR TITLE
Add inline starlist display

### PR DESCRIPTION
**Pull request by stefanv**
Peek 2020-06-11 00-46

### CODE REVIEW

**Comment by dmitryduev** [comment]
Once the starlist is displayed, should the button be changed to "HIDE STARLIST" (with the appropriate behavior)?

**Comment by stefanv** [comment]
Good suggestion, @dmitryduev: done.

**Comment by stefanv** [comment]
This is mainly to help people who have the finding chart get an easy to copy-paste copy of the list, otherwise they have to parse the JSON themselves, since the PDF does not allow copy.

Happy to have this moved to wherever.

**Comment by acrellin** [comment]
Merging for now, and we can move later if/when relevant.

**Pull request merged**
