### PR TITLE
Add classification origin column

### PR DESCRIPTION
**Pull request by bfhealy**
This PR adds a classification origin column and modifies the tests accordingly. This change will be useful e.g. for color-coding classifications by their source.

Mentioning @Theodlz for frontend help (thanks in advance!).

### CODE REVIEW

**Comment by Theodlz** [comment]
I added some basic frontend @bfhealy @mcoughlin, let me know if you are expecting something different.

**Comment by bfhealy** [comment]
Thanks very much @Theodlz! Glad to see the color coding shows both on the individual source page and the sources list. I think that will be useful for scanners. @mcoughlin, Do you think the current color coding for scope classifications is different enough compared to the default?

Screen Shot 2023-05-31 at 10 05 47 AM

**Review by mcoughlin — APPROVED** [review]
LGTM

**Comment by mcoughlin** [comment]
@bfhealy Please update fork and update the revision head in alembic and we will get this merged.

**Pull request merged**
