### PR TITLE
do not split date if want full date

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR only uses the split on the date if specifying date format (need full isot in some cases).

You might have a better way of doing this @Theodlz

### CODE REVIEW

**Comment by Theodlz** [comment]
@mcoughlin so this piece of code is already in an if statement where we do things differently for followup requests and forced photometry right? If so, just leave the time for followup requests and only pop it out for the forced phot.

**Comment by mcoughlin** [comment]
You do them for both forced photometry and normal requests @Theodlz

**Comment by Theodlz** [comment]
> You do them for both forced photometry and normal requests @Theodlz

yes that's what I meant. Like in the existing if statement, you can just remove the split when its a followup request in general and the field is called start_date or end_date, like not sure we really need to check that its format === date

**Comment by Theodlz** [comment]
just if follow-up request and not forced photometry, do the isostring but no split ?

**Comment by Theodlz** [comment]
for forced phot we def not need the time its a large enough time range, but for the follow-up requests I feel like it's pretty much always useful

**Comment by mcoughlin** [comment]
Any chance you can just fix it how you want it @Theodlz ?

**Comment by Theodlz** [comment]
Sure, will do in a little bit.

**Pull request merged**
