### PR TITLE
Add sidebar

### PR DESCRIPTION
**Pull request by acrellin**
This PR adds a collapsible sidebar with links to the app's main pages.

The footer is removed, and SkyPortal info is moved to an About page, with links in the sidebar and profile dropdown.

image

### CODE REVIEW

**Comment by dmitryduev** [comment]
Niiice!! Great work, @acrellin!!

**Comment by dmitryduev** [comment]
One request: can we please ditch the sticky footer (or at least make it configurable)? Takes up a lot of space and is not super informative.

**Comment by acrellin** [comment]
@dmitryduev how about making it really small (like a single text line
height)?

**Comment by acrellin** [comment]
Or we can just remove it and put the skyportal version number in the top banner somewhere

**Comment by acrellin** [comment]
@dmitryduev 
image

**Comment by dmitryduev** [comment]
Thanks @acrellin! I like it like that much more :) Let's discuss some other potential changes to the footer (and header) tomorrow.

**Comment by acrellin** [comment]
Here's with no footer and the SkyPortal info moved up top:
image

**Comment by dmitryduev** [comment]
I actually like it even more without the footer!
How would you feel about moving the version and the link for filing issues (+ maybe adding some additional info) to a dedicated "About SkyPortal" page or something along these lines?

**Comment by acrellin** [comment]
Good idea, will do.

**Comment by acrellin** [comment]
New About page with links in profile drop-down & sidebar:

image

**Comment by acrellin** [comment]
Sidebar open/close action: 

sidebar

**Comment by acrellin** [comment]
This is ready for review. Tests are passing locally; selenium tests have been very finicky on Travis recently (will continue addressing this).

**Pull request merged**
