### PR TITLE
On top spectra

### LINKED ISSUE #1844: Feature request "in front' spectra
Currently when there are multiple spectra plotted, the "in front" ordering is fixed.  I would like to control the "in front" ordering.  One way to do this is through the order of toggling of spectra visibility.

### PR DESCRIPTION
**Pull request by jadalilleboe**
Allows the user to choose which spectra should be displayed on top, closes #1844 
ezgif com-gif-maker (9)
@guynir42 you were right, there was a much easier way to do this within bokeh!

### CODE REVIEW

**Review by guynir42 — COMMENTED** [review]
This looks a whole lot better, thanks! One thing I did notice is that the grid lines get in front of the spectrum. You should probably find their component and push it back to the background explicitly.

**Comment by jadalilleboe** [comment]
@guynir42 Yeah you're right. done

**Comment by jadalilleboe** [comment]
Screen Shot 2022-04-22 at 2 26 23 PM
grid does not go over spectra now

**Review by guynir42 — APPROVED** [review]
Looks great. Thanks!

**Pull request merged**
