### PR TITLE
Fix upload photometry front-end tests: use Instrument filter list specified in test fixtures

### PR DESCRIPTION
**Pull request by acrellin**
Fixes test failures introduced in https://github.com/skyportal/skyportal/commit/ee2d8894b262cd4b61bcf0e9a63ca3730c931e3f

### CODE REVIEW

**Comment by acrellin** [comment]
Travis is green, only GA failure is `test_news_feed_prefs_widget`

**Comment by acrellin** [comment]
Merging as this fixes consistent failures on master

**Comment by dannygoldstein** [comment]
@acrellin This does not fix the issue. What is happening is that the mouse moving is selecting not SEDM but the adjacent ZTF in the dropdown even though it is supposed to be selecting SEDM. The wrong instrument is being selected. So the test is not uploading photometry to the requested instrument. The filter checking caught this before - the test tried to upload 'sdssg' to ZTF, failing. If the right instrument (SEDM) is selected then this does not happen.

**Comment by dannygoldstein** [comment]
(Sometimes SEDM is correctly selected, in which case this new vesion (uploading ztfg to SEDM) will fail).

**Comment by acrellin** [comment]
@dannygoldstein then that's another issue, but the instrument that *was* being selected had the wrong filters. this fixed that. those tests now pass on CI

**Comment by dannygoldstein** [comment]
test_upload_photometry_multiple_groups

The correct instrument (SEDM) is sandwiched between two adjacent ZTFs. Sometimes those are selected instead of SEDM. The tests here will now pass when that happens. However, sometimes the correct instrument (SEDM) will be selected. SEDM does not have a ztfg. So when that happens this test will fail. So this is switching out one of these cases for another...

**Comment by dannygoldstein** [comment]
The source of this bug is Material UI. There are animations after both scrolling and clicking that need to be waited for, or else the wrong menu element will be selected. The current tests clicked on `//body` immediately after the select element, which caused the wrong select element to end up being chosen (the selected one ended up always being 18 elements behind the targeted one). This is fixed in #889.

**Pull request merged**
