### PR TITLE
Filter by Spectra date

### PR DESCRIPTION
**Pull request by bparazin**
Closes https://github.com/skyportal/skyportal/issues/2337

I added 2 inputs to filter source list so you can filter to all with a spectra taken before or after a certain date
image

### CODE REVIEW

**Comment by bparazin** [comment]
image
Another image showing it filtering out one of the 2 sources since its most recent spectra is from 8/19/19

**Comment by bparazin** [comment]
@stefanv can you please take a look?

**Comment by stefanv** [comment]
Looks okay to me, but the handler docstring needs to be updated to match.

**Comment by bparazin** [comment]
Pushed a commit which I believe addresses @stefanv's comment

**Comment by bparazin** [comment]
Any other comments on this one?

**Comment by acrellin** [comment]
@stefanv Mind taking a quick look?

**Pull request merged**
