### PR TITLE
Underflow from small skymap values

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR prevents underflow from small skymap values.

### CODE REVIEW

**Review by Theodlz — COMMENTED** [review]
2 questions before I approve:
- We shouldn't have negative values at all right? Why do we need this intersection here?
- Is 1e-20 small enough? Looking at the database most skymaps had a lot of values under 1e-20. Especially large ones. Could we maybe lower that number to something much smaller, like maybe 1e-200?

**Comment by Theodlz** [comment]
> 2 questions before I approve:
> 
> * We shouldn't have negative values at all right? Why do we need this intersection here?
> * Is 1e-20 small enough? Looking at the database most skymaps had a lot of values under 1e-20. Especially large ones. Could we maybe lower that number to something much smaller, like maybe 1e-200? It's not very risky, and we avoid changing the skymap too much.

**Comment by mcoughlin** [comment]
@Theodlz Good point, let's just make it 1e-200 and set them all to 0. Wanna take care of that?

**Comment by Theodlz** [comment]
@mcoughlin sure! Let me try right now.

**Comment by Theodlz** [comment]
Feeling like taking risks today. Tried 10^-300, which was enough to get the 2 buggy skymaps I had to work (i did it manually in postgres last time) just fine so it seems like a good number 😉. Let's see if the tests are still happy with that.

**Pull request merged**
