### PR TITLE
Allow group admins to manage other group members

### PR DESCRIPTION
**Pull request by acrellin**
This PR updates the permissions regarding modifying group members' admin status such that any group admin (regardless of ACLs) can grant/revoke the admin status of other group members, or remove users entirely.

Closes https://github.com/fritz-marshal/fritz/issues/191

### CODE REVIEW

**Comment by stefanv** [comment]
That's an odd asymmetry; who requested this?

**Comment by acrellin** [comment]
@stefanv Any group admin can already add users & make them an admin in the process via NewGroupUserForm, but they can't update their admin status after the fact or remove them from the group to be able to re-add them as an admin. That seems a bit backwards to me (and there's a linked issue that was complaining about this), thus this PR.

**Comment by stefanv** [comment]
I just think, in general, if users can do something they should be able to undo it.  Otherwise they accidentally click something, and then need to get help to fix it.

**Comment by acrellin** [comment]
@stefanv but that currently doesn't apply to adding new group users, because only those with particular ACLs can remove users from groups

**Comment by acrellin** [comment]
@stefanv but yes, I agree in general, but apparently at least one PI doesn't 😉   thus the weird requirements here.

**Comment by stefanv** [comment]
Maybe we should mention to them what awkwardness this poses and ask them to re-assess.

**Comment by acrellin** [comment]
@stefanv  I can see the case for it here -- you may want to grant group admin status to a member so they can take care of certain tasks (e.g. reviewing save requests) but not let them go rogue and revoke *your* admin status.

**Comment by stefanv** [comment]
Then maybe our permission granularity should be increased?  Asymmetric permissions just seem like they're going to cause headaches.

**Comment by acrellin** [comment]
But there are already plenty of areas where users are able to post data but
not necessarily delete them, right?

**Comment by stefanv** [comment]
Really?

**Comment by acrellin** [comment]
@stefanv it sounds like your objection is actually to what's already implemented, not this PR then. Let's discuss in the next meeting.

**Comment by stefanv** [comment]
Yes, I was quite surprised!  But you're absolutely right: there's no problem with the PR, we just need to figure out if this, in general, is the way to go.

**Comment by acrellin** [comment]
@stefanv  I've done away with the asymmetrical permissions here

**Review by stefanv — APPROVED** [review]

**Review by kmshin1397 — APPROVED** [review]

**Review by dmitryduev — APPROVED** [review]

**Pull request merged**
