### PR TITLE
Add K Band magnitude column to galaxy table

### LINKED ISSUE #2525: K-band galaxy magnitude
Another common(ish) column available in galaxy catalogs is K-band magnitude. Should add magk as a column to the Galaxy table:
https://github.com/skyportal/skyportal/blob/master/skyportal/models/galaxy.py#L30

### PR DESCRIPTION
**Pull request by jadalilleboe**
Closes #2525 

Adds a K Band magnitude column to the galaxy table, and adds an extra optional parameter for K Band Magnitude in the galaxy API.

### CODE REVIEW

**Comment by mcoughlin** [comment]
@profjsb the migrations error looks familar (i.e. i get the same issue building on my laptop and currently add --force to the npm install call).

**Comment by mcoughlin** [comment]
@jadalilleboe Also remember to fill in the extra optional parameter in the galaxy.py API.

**Comment by guynir42** [comment]
@jadalilleboe try to merge master (`git pull upstream master`) it may shake something loose.

**Comment by jadalilleboe** [comment]
> @jadalilleboe try to merge master (`git pull upstream master`) it may shake something loose.

doesn't look like anything changed, is the error possibly because we're using an older version of mui-datatables? Looks like it's up to [version 4.0.0 now](https://github.com/gregnb/mui-datatables/releases)

**Comment by profjsb** [comment]
@jadalilleboe  can you give me collaborator status on your fork https://github.com/jadalilleboe/skyportal.git? I can push in the latest changes to master.

**Comment by profjsb** [comment]
failures unrelated

**Comment by profjsb** [comment]
Does the CLU data in `db_demo.yaml` need to be updated with a K-band mag column?

**Comment by mcoughlin** [comment]
I don't think our demo data has it, it's in other catalogs though, but I don't think important to have it here.

**Comment by profjsb** [comment]
LGTM!

**Pull request merged**
