### PR TITLE
Basic DB stats page

### PR DESCRIPTION
**Pull request by acrellin**
db_stats

Closes https://github.com/fritz-marshal/fritz/issues/162

### CODE REVIEW

**Comment by acrellin** [comment]
Alerts-related stats will be implemented in Fritz extension after this is merged.

**Comment by acrellin** [comment]
For reviewers:  Currently, there is no link to this page, so you have to know the URL to access the page, but it's viewable by anyone. I was unsure of if/how we want to restrict access here, so I welcome suggestions.

**Review by dmitryduev — CHANGES_REQUESTED** [review]
Looks good, thanks @acrellin. One request: please add comma separators to the numbers in the table, otherwise would be pretty hard to gauge things in prod.

**Comment by acrellin** [comment]
@dmitryduev done: 
image

**Comment by stefanv** [comment]
Looks neat!  @acrellin can we use descriptive sentences for the fields?  I.e., translate `numObjs` to `Number of objects`.

**Comment by acrellin** [comment]
@stefanv  Yes, I was thinking about how to do that and keep the front-end totally general so it can easily render arbitrary data, but I suppose we can just use keys like "Number of candidates" as long as we can have object properties with spaces in the OpenAPI spec

**Comment by stefanv** [comment]
Or just do some standard replacement of `_` with ` ` and capitalize the first letter.

**Comment by acrellin** [comment]
@stefanv done: 
db_stats_page
db_stats_api_docs

**Comment by acrellin** [comment]
With one million rows in the candidates table:
``` python
In [5]: %timeit perform_stats_queries()              
171 ms ± 2.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Review by kmshin1397 — APPROVED** [review]
LGTM!

**Comment by acrellin** [comment]
Conditionally-rendered link to DB Stats page in Sidebar:
image

**Review by dmitryduev — APPROVED** [review]
Looks great, merging!

**Pull request merged**
