### PR TITLE
Update user ACLs and Roles via user management page

### PR DESCRIPTION
**Pull request by acrellin**
This PR expands the user management page by adding functionality for editing user roles and ACLs.

ACLs/roles handlers and associated endpoints are added.

Partially addresses https://github.com/skyportal/skyportal/issues/914

edit_user_roles_acls

### CODE REVIEW

**Review by profjsb — APPROVED** [review]
Looks great. Might want to put legend/key at the bottom of the page to explain what group of ACLs are bundled into each Role type. Also explain in a sentence that the the ACLs are combined with an OR (ie. it's a union).

**Comment by acrellin** [comment]
> Looks great. Might want to put legend/key at the bottom of the page to explain what group of ACLs are bundled into each Role type. Also explain in a sentence that the the ACLs are combined with an OR (ie. it's a union).

@profjsb good call, will add :+1:

**Comment by acrellin** [comment]
Sole failure is unrelated: `test_submit_annotations_filtering`

**Comment by acrellin** [comment]
Added help icons w/ tooltips describing the ACLs associated with each role, and more information about the additional ACLs column:
user_mgmt_page_tooltips

**Review by dmitryduev — APPROVED** [review]
LGTM!
Two minor comments:
- It is possible to shoot yourself in the foot and, e.g., remove your System admin role. Should we allow that? (I guess it's fine)
- I guess this won't be an issue when we switch to MUI datatable:
image

**Comment by acrellin** [comment]
@dmitryduev thanks for the review. I opened an issue for using mui-datatables. Do you want to see any changes regarding your first comment before we merge?

**Comment by dmitryduev** [comment]
@acrellin no, looks good. I guess there's always a way to shoot yourself in the foot, so just need to be careful :)

**Pull request merged**
