### PR TITLE
JS component tree (Dependency-cruiser)

### PR DESCRIPTION
**Pull request by KodeurFou**
Here is the version of dependency cruiser I used

that the site I used to generate the .svg
https://www.npmjs.com/package/dependency-cruiser

lissue we where discussing it on :
https://github.com/skyportal/skyportal/issues/3846

### CODE REVIEW

**Comment by mcoughlin** [comment]
@KodeurFou please remove the ^ in the dependencies.

**Comment by mcoughlin** [comment]
@Theodlz I think we should put something like this into the contribution docs

**Comment by Theodlz** [comment]
@mcoughlin though I do love the idea, I feel like how that specific graph looks makes it pretty much unreadable, + we want this to be regenerated automagically along with the docs or smth, we can't commit this as is because it will just be incorrect after one frontend PR.

**Comment by mcoughlin** [comment]
@Theodlz Ok maybe have an issue referencing the idea? Would be great to have it generated at doc creation time...

**Comment by Theodlz** [comment]
Good idea, doing that now

**Pull request closed without merging**
