### PR TITLE
sinceDaysAgo float

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR makes fractional days for sinceDaysAgo possible.

### CODE REVIEW

**Comment by Theodlz** [comment]
@mcoughlin nothing else needed for it to work? I noticed that it didn't work in prod yet, just wanted to make sure this was related.

**Comment by mcoughlin** [comment]
I honestly can't quite tell, but for sure this was a problem.

**Comment by Theodlz** [comment]
Got it, let's merge this then.

**Review by Theodlz — APPROVED** [review]
LGTM

**Comment by Theodlz** [comment]
@mcoughlin it's a frontend refresh issue. I can see that the right data is loaded in the console, but it doesnt refresh the dashboard. Probably just needs a nice useEffect

**Comment by mcoughlin** [comment]
Can you tell where?

**Comment by Theodlz** [comment]
let me take a look

**Comment by Theodlz** [comment]
genuinely confused, as this does work just fine locally, hmmm. Maybe an issue with the existing user preferences in prod (that were missing those new keys) that I don't have on a brand new database. Will keep looking

**Comment by Theodlz** [comment]
yeah an odd rendering issue. Using the search bar rerenders the list hmmmm

**Comment by Theodlz** [comment]
@mcoughlin I think this should help

**Pull request merged**
