### PR TITLE
Forced photometry queue

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR modifies forced photometry such that the retrieval is automated.

### CODE REVIEW

**Comment by Theodlz** [comment]
Hi @mcoughlin. 

I have one question, why an API + Service in this scenario where we already have the concept of transactions/followup requests with a status? From the frontend of skyportal's API, we could directly post the request to the database with a status like "processing", and this microservice could just poll from the DB and go through the requests to process, rather than add the complexity of running a multithreaded service like we do here right?

**Comment by mcoughlin** [comment]
@Theodlz that could work, although I think it is easier to keep track of things queue style, if only because our other services seem to handle things well this way. I think this also will likely make for easier user polling of status; we will need some better way for users to be able to track the status of their requests in general.

**Comment by Theodlz** [comment]
Let's try this then. I would try not to add to many multithreaded services in the future however. So let's get this one in, but we should think about single threaded model for this one at some point.

**Review by Theodlz — APPROVED** [review]
LGTM. Only comment is what about the frontend now that you removed the GET methods? People might be confused if they still see the button. At least we should make sure to display a decent error message that makes it clearer that the GET might be handled automatically.

**Comment by mcoughlin** [comment]
@Theodlz shouldnt be a problem since we deleted the GET

**Comment by Theodlz** [comment]
Ah you mean that the frontend checks if these methods are available before showing (or not) the associated buttons? In that case feel free to merge.

**Comment by mcoughlin** [comment]
@Theodlz Yeah exactly.

**Pull request merged**
