### PR TITLE
Require Python >=3.8

### PR DESCRIPTION
**Pull request by acrellin**
Closes https://github.com/skyportal/skyportal/issues/1628

### CODE REVIEW

**Comment by stefanv** [comment]
Thanks, Ari, this looks good.  Is the version checker here or in BL?  That one needs to be updated too.

**Comment by acrellin** [comment]
> Thanks, Ari, this looks good. Is the version checker here or in BL? That one needs to be updated too.

@stefanv it's updated in BL here: https://github.com/cesium-ml/baselayer/pull/194

**Comment by stefanv** [comment]
OK, merged on the BL side; we can pin and merge this one too.

**Comment by acrellin** [comment]
Pinned latest BL master

**Comment by acrellin** [comment]
Failure unrelated (known flaky test: `FAILED skyportal/tests/frontend/test_sources.py::test_regular_user_cannot_delete_unowned_comment`)

**Pull request merged**
