### PR TITLE
Fix streams fetching in useEffect to avoid infinite loop when streams table is empty

### PR DESCRIPTION
**Pull request by acrellin**

### CODE REVIEW

**Review by dannygoldstein — APPROVED** [review]

**Comment by dannygoldstein** [comment]
What happened to the travis build here ?

**Comment by acrellin** [comment]
@dannygoldstein no idea. @stefanv ?

**Comment by dannygoldstein** [comment]
@acrellin 

Seeing the same failure:

```
--------------------------------------------------------------------------------
FAIL: skyportal/tests/frontend/test_user_management.py:34 in test_add_user_to_group

        driver.get(f'/become_user/{super_admin_user.id}')
        driver.get('/user_management')
        driver.wait_for_xpath(
>           f"//div[@id='deleteGroupUserButton_{user.id}_{public_group.id}']"
        )


```

**Comment by acrellin** [comment]
@dannygoldstein this is now passing consistently locally

**Comment by acrellin** [comment]
@dannygoldstein this has been further robustified and I don't see any way this is possibly still an issue. the failure must be related to something else. please merge if happy with changes here

**Comment by acrellin** [comment]
Closing and moving to an upcoming user management page PR to avoid merge conflicts

**Pull request closed without merging**
