### PR TITLE
Grab SDSS and DR8 thumbnails if they don't exists for some reason

### PR DESCRIPTION
**Pull request by dmitryduev**
Addresses https://github.com/skyportal/skyportal/issues/2254.

### CODE REVIEW

**Review by acrellin — COMMENTED** [review]
Looks good but we should take care that simultaneous fetches by different users don't trigger duplicate thumbnail generation processes.

**Comment by dmitryduev** [comment]
Hey @acrellin, good to e-see you :)
How should we do that? I don't see any specific logic for PS1 thumbnails, and this basically does the same thing. Also, some of the calls would just fail - the db would complain and won't let the transaction complete, no?

**Comment by acrellin** [comment]
> Hey @acrellin, good to e-see you :)
> How should we do that? I don't see any specific logic for PS1 thumbnails, and this basically does the same thing. Also, some of the calls would just fail - the db would complain and won't let the transaction complete, no?

Yeah, just thinking out loud -- whatever failsafe we might add should be applied to PS1 generation, too. Maybe just a unique constraint that would cause a SQLA error upon attempting to insert a duplicate?

**Comment by dmitryduev** [comment]
@acrellin would that always happen [here](https://github.com/skyportal/skyportal/blob/master/skyportal/models.py#L1042)?

**Comment by dmitryduev** [comment]
Failure in `test_token_user_big_post` - unrelated.

**Comment by acrellin** [comment]
@dmitryduev I don't think so -- we don't have any unique constraints on thumbnails, but adding this should do the trick: 
``` python
Thumbnail.__table_args__ = (
    sa.Index(
        "thumbnail_deduplication_index",
        Thumbnail.obj_id,
        Thumbnail.type,
        unique=True,
    ),
)
```

**Comment by dmitryduev** [comment]
@acrellin ah, you're right. We should be careful with this though: remember https://github.com/skyportal/skyportal/issues/1361. + this will effectively disable multi-epoch thumbnail for now. 
I would advocate for merging this as is, as there have been complains about the missing thumbnails, but we should really get back to 1361...
@stefanv what do you think?

**Comment by stefanv** [comment]
As long as duplicates don't cause issues (which I don't think they will), how about we add this for now and file an issue to discuss duplicate handling?

**Comment by dmitryduev** [comment]
👍🏻 
@acrellin?

**Comment by acrellin** [comment]
Sounds good!

**Review by acrellin — APPROVED** [review]

**Pull request merged**
