### PR TITLE
Add scaffold for GeoJSON plot

### PR DESCRIPTION
**Pull request by stefanv**
@lpsinger @mcoughlin 

The plot is rendered at `/test_geojson`.

Also see `GcnEventPage.jsx`

globe-turn

### CODE REVIEW

**Comment by stefanv** [comment]
Again just riffing off of @mcoughlin's GcnEventsPage, added an example here of interactive plotting of galaxies on a sphere with labels (see PR description).

**Comment by profjsb** [comment]
Very cool. Got some "let's plan to destroy the Death Star" vibe here. image

**Comment by stefanv** [comment]
clickable-sources

After a bit more d3 wrangling, points behind the sphere are hidden, and you can navigate to the relevant source by clicking on it.

**Comment by mcoughlin** [comment]
@stefanv Amazing. Would it be straightforward to show off the instrument contours too?
https://github.com/skyportal/skyportal/blob/master/skyportal/handlers/api/instrument.py#L331
For the demo you are doing, you could just plot the fields. In the MVP, we want to be plotting only the fields attached to either the planned observations (https://github.com/skyportal/skyportal/blob/master/skyportal/handlers/api/observation_plan.py#L144 or the executed observations (https://github.com/skyportal/skyportal/blob/master/static/js/components/GcnEventPage.jsx#L262).

**Comment by mcoughlin** [comment]
@stefanv fine with me!

**Comment by mcoughlin** [comment]
@stefanv Closing this now that essential pieces are either merged or in progress elsewhere.

**Pull request closed without merging**
