### PR TITLE
index spatial database objects by ra,dec using q3c

### PR DESCRIPTION
**Pull request by dannygoldstein**

### CODE REVIEW

**Comment by acrellin** [comment]
@dannygoldstein is this PR ready for review?

**Comment by dannygoldstein** [comment]
Yes, if the project commits to using q3c. In #112 @profjsb said he was cool with integrating q3c into the project but in cesium-ml/baselayer#59 @stefanv said it should be optional

**Comment by acrellin** [comment]
@dannygoldstein the changes to the db commands are failing on Travis. Looks
like it might be due to the baselayer changes.

**Comment by dannygoldstein** [comment]
I can fix it, but can @profjsb and @stefanv to weigh in on the q3c issue before I move forward?

**Comment by dannygoldstein** [comment]
I moved the code to automatically install q3c to the skyportal layer, and overrode `db_init` in the `Makefile`.

**Comment by acrellin** [comment]
@dannygoldstein where do things stand here? Do you want a hand getting this working on Travis?

**Comment by dannygoldstein** [comment]
Yeah that would be great. Thanks. I'm working on this now.

**Comment by acrellin** [comment]
@dannygoldstein great, how can I help?

**Comment by dannygoldstein** [comment]
nothing for the moment. will let you know soon. going to try to reproduce the travis errors locally on my machine via docker ...

**Comment by dannygoldstein** [comment]
@acrellin  in travis,  psql 9.6 is installed but pg_config returns a lib linked to v11. why is this?

**Comment by dannygoldstein** [comment]
hi @acrellin, could you show me swap out the travis psql version from travis-9.6 to the postgresql-q3c provided via apt? https://docs.travis-ci.com/user/database-setup/ indicates I should be able to do it, but I can't quite figure it out...

**Comment by acrellin** [comment]
hi @dannygoldstein, see the slack channel for further details on installing
postgresql 10 on Travis

**Pull request closed without merging**
