### PR TITLE
Update config to provide defaults where possible, otherwise use `cfg.get`

### PR DESCRIPTION
**Pull request by stefanv**
This requires eyes from @mcoughlin, @guynir42, @profjsb, and @Theodlz, since it touches pieces of code you wrote.

### CODE REVIEW

**Comment by stefanv** [comment]
The usage of `cfg.get` should be extremely limited for SkyPortal, since our configuration file defines defaults in almost all cases.

**Comment by guynir42** [comment]
> The usage of `cfg.get` should be extremely limited for SkyPortal, since our configuration file defines defaults in almost all cases.

I think that really depends. Just because our config file defines a bunch of stuff doesn't mean other people can't delete it and leave it blank. 

In my opinion, whenever you can supply a reasonable default you should do that, even though we define most of that stuff in the config.

**Comment by stefanv** [comment]
We *do* supply reasonable defaults (in `config.yaml.defaults`), and you cannot just delete those values so easily.

**Comment by stefanv** [comment]
What you don't want to do is to provide all defaults twice, once in the config and another time in the code.  I already found instances where they were out of sync.

**Comment by stefanv** [comment]
If you leave a value blank, it can still be accessed using `cfg['key']`, btw.

**Review by profjsb — APPROVED** [review]
LGTM

**Comment by stefanv** [comment]
Thanks for that last commit, @guynir42!

**Pull request merged**
