### PR TITLE
Add type column to user notification table

### LINKED ISSUE #2245: Add `type` column to `UserNotification` table
Without it, the Slack integration has to parse the notification text to know if it is a mention, e.g.

### PR DESCRIPTION
**Pull request by jadalilleboe**
Closes #2245

### CODE REVIEW

**Comment by mcoughlin** [comment]
@jadalilleboe Is it maybe worth using this same PR to modify https://github.com/skyportal/skyportal/blob/master/skyportal/models/user_notification.py#L124 to use your new column and check based on the flag ?

**Comment by jadalilleboe** [comment]
@mcoughlin Yeah for sure! I wasn't sure where this was supposed to be used.

**Comment by mcoughlin** [comment]
@jadalilleboe Ah yeah the main goal is to remove these is_* statements:
https://github.com/skyportal/skyportal/blob/master/skyportal/models/user_notification.py#L90
which I shamefully wrote ;)

**Comment by mcoughlin** [comment]
@guynir42 @jadalilleboe  for the notification types, should we make them camel case maybe?

**Comment by jadalilleboe** [comment]
ye

**Comment by jadalilleboe** [comment]
@mcoughlin Is there anything else that should be added here? Or do you think this is ready for review?

**Review by mcoughlin — APPROVED** [review]
Thanks for fixing that @jadalilleboe !

**Review by guynir42 — APPROVED** [review]
LGTM. Please make sure the migration hash is up to date before merging.

**Pull request merged**
