### PR TITLE
Fix serialization of JSON types to postgresql in spectrum upload

### PR DESCRIPTION
**Pull request by dannygoldstein**
@dmitryduev Can you deploy this on private once green? 

Fixes the upload problem encountered by @scizen9 and related to 

https://github.com/skyportal/skyportal/pull/977#discussion_r496302244

### CODE REVIEW

**Review by dmitryduev — APPROVED** [review]
LGTM. Is this the only special case you’d anticipate ?

**Comment by dmitryduev** [comment]
@dannygoldstein can this be an astropy.time.Time object, for instance?

**Comment by dannygoldstein** [comment]
@dima this is ready now. This is the only special case I anticipate as the astropy.Time stuff is outside of the fits header standard and the pyyaml standard.

**Review by stefanv — APPROVED** [review]

**Comment by dannygoldstein** [comment]
Needed to make one more change. This should fix the failures...

**Comment by dannygoldstein** [comment]
Merging as travis is green, there are two check marks, and failure on GA is unrelated

**Comment by dannygoldstein** [comment]
Merging as travis is green, there are two check marks, and failure on GA is unrelated

**Pull request merged**
