### PR TITLE
Fix and improve docker-compose deployment

### LINKED ISSUE #377: docker-compose enhancements requests
- Can you add
```
version: "3.3"

services:
```
to the top of the `docker-compose.yaml` file? That will ensure the "skyportal_default" network gets created so that other dockerized services running on the same machine may connect to it and talk to skyportal.

- Please also add persistent volumes so that the data do not get wiped out every "docker-compose down".

### PR DESCRIPTION
**Pull request by stefanv**
- Update docker-compose file to v3
- Upgrade postgres, and add now-required password
- Store database data in a volume that lives outside of web container
- Add deployment docs
- Update node to 12 in Docker images
- Add config.yaml to .dockerignore so it doesn't get added to images,
  accidentally exposing tokens

Closes #377

### CODE REVIEW

**Comment by profjsb** [comment]
@dmitryduev @acrellin are we ready to merge this?

**Comment by stefanv** [comment]
@dmitryduev Looking at your PR, I think there is only one change that I don't have (forcing restart of postgres).  Is that one important?

**Comment by dmitryduev** [comment]
Looks great! My only concern is with `docker.yaml` and `docker-compose.yaml`: if you change those, which you should, what happens the next time you `git pull`? Wouldn't `git` complain? That's why I wanted to rename them into *.defaults

**Comment by dmitryduev** [comment]
As for `restart: always` -- I would add it, find it very useful. Otherwise if the db container dies for some reason, you'll have to manually restart it.

**Comment by stefanv** [comment]
@dmitryduev I had no problem loading demo data locally; did you test it and experience problems?

For Fritz, we probably want to make a new docker-compose config that [extends](https://docs.docker.com/compose/extends/#multiple-compose-files) the SkyPortal and Kowalski ones and a docker.yaml (or fritz.yaml), mounting the latter into the skyportal container as config.yaml.

I've added restarting to the db container.

**Comment by dmitryduev** [comment]
@stefanv yea, I tried running it inside a container on my mac and on a linux machine, hangs every time.
Agree on the fritz point.

**Pull request merged**
