### PR TITLE
Be less restrictive on source naming

### PR DESCRIPTION
**Pull request by dmitryduev**
Currently, we have:
```python
(r'/api/sources(/.*)?', SourceHandler)
```
but then we do
```python
(r'/api/sources(/[0-9A-Za-z-_]+)/photometry', ObjPhotometryHandler)
```
which seems unreasonable.

### CODE REVIEW

**Comment by dmitryduev** [comment]
Are there any reasons (that I'm missing) why, e.g., `ZTFJ030423.02-213512.7` would be a bad name?

**Comment by acrellin** [comment]
The original motivation was to facilitate regex pattern matching (i.e. don't gobble up the "/photometry" into the source ID), but if it's smart enough to not do that, then this seems fine to me

**Comment by dmitryduev** [comment]
@stefanv can you comment on this please?

**Review by acrellin — APPROVED** [review]

**Comment by stefanv** [comment]
Hrm, how does the `.*` not gobble up the rest of the URL?  I read something about the `.*` being problematic, but I haven't had a chance to resurface that webpage yet.

**Review by acrellin — APPROVED** [review]

**Comment by dmitryduev** [comment]
Failure unrelated:

```
FAILED skyportal/tests/api/test_photometry.py::test_token_user_big_post - ass...
= 1 failed, 434 passed, 3 xfailed, 1 xpassed, 200 warnings, 1 rerun in 2250.46s (0:37:30) =
--------------------------------------------------------------------------------
FAIL: skyportal/tests/api/test_photometry.py:1460 in test_token_user_big_post
```

**Review by kmshin1397 — APPROVED** [review]

**Pull request merged**
