### PR TITLE
Implement ReactMarkdown in the Comment fields (+ emojis!).

### PR DESCRIPTION
**Pull request by mcoughlin**
Screen Shot 2020-08-26 at 9 44 36 PM

### CODE REVIEW

**Comment by dannygoldstein** [comment]
Tried rerunning this, but I think these failures may be real as `NewsFeed.jsx` and `CommentList.jsx` are both modified here.

```
=========================== short test summary info ============================
FAILED skyportal/tests/frontend/test_newsfeed.py::test_news_feed - selenium.c...
FAILED skyportal/tests/frontend/test_newsfeed.py::test_news_feed_prefs_widget
FAILED skyportal/tests/frontend/test_sources.py::test_comment_groups_validation
FAILED skyportal/tests/frontend/test_sources.py::test_super_user_can_delete_unowned_comment
FAILED skyportal/tests/frontend/test_sources.py::test_delete_comment - seleni...
FAILED skyportal/tests/frontend/test_sources.py::test_regular_user_cannot_delete_unowned_comment
```

**Comment by mcoughlin** [comment]
@dannygoldstein @stefanv I also see failures locally, although they are just timeout exceptions. The comments seem to delete fine when I just click the delete button, so it is a bit weird. Is there anything you suggest trying here? The clicking stuff is nice but a bit opaque.

**Review by kmshin1397 — CHANGES_REQUESTED** [review]
Hi @mcoughlin, the tests were failing because switching the comments to use ReactMarkdown changed the DOM structure a little so the tests couldn't find the comments they were looking for. 

I just went ahead and opened a [PR ](https://github.com/mcoughlin/skyportal/pull/2) to your PR branch to address the tests as well as to merge in the lastest master (there's been a lot of changes in the past week so I figured it was easiest for me to just take care of that for you). Finally, there were a couple style tweaks I added (basically making the comments more compact, which was one of the changes that went in the last week) to your code. 

Overall, LGTM! I think once you look over and merge in my PR to your PR, we can merge this into master. Sorry I took so long to review this - I somehow completely missed that I was tagged as the reviewer on this.

**Comment by stefanv** [comment]
@kmshin1397 Can you mention this PR in your PR so that it appears here for reference?

**Review by kmshin1397 — APPROVED** [review]

**Comment by kmshin1397** [comment]
@stefanv @dannygoldstein One of you want to review and merge this?

**Pull request merged**
