### PR TITLE
Refactor models.py into a submodule

### PR DESCRIPTION
**Pull request by stefanv**
models.py was deleted

### CODE REVIEW

**Comment by dmitryduev** [comment]
Impressive 
image

**Comment by stefanv** [comment]
I separated them for now to make it clear where everything comes from, but if you prefer to have them all in one spot that's easy to add. Let me know your preference!

**Comment by acrellin** [comment]
@stefanv Of course! 

Regarding separate imports for BL models, as long as it's pretty obvious which models come from where, I'm fine with having them separated like this. If devs will need to be looking it up frequently (where do I import ___ from again??), it might be worth importing them all in the SP models init. Thoughts?

**Comment by acrellin** [comment]
@stefanv What about changing the imports in the handlers back to being all from the SP models module?

**Comment by stefanv** [comment]
> @stefanv What about changing the imports in the handlers back to being all from the SP models module?

OK, sure, done.  I left the imports in `skyportal.models` itself alone, since they are *part* of `skyportal.models`.

**Pull request merged**
