### PR TITLE
Python side field picking for obsplan

### PR DESCRIPTION
**Pull request by guynir42**
first attempt at making a python side obs plan

### CODE REVIEW

**Comment by guynir42** [comment]
@mcoughlin don't "review" yet, but have a look to see if anything looks like a bug...

**Comment by Theodlz** [comment]
Hi Guy. This looks very nice. I'll play around with the code today to compare the skyportal with db, skyportal with python and gwemopt implementations.

**Comment by mcoughlin** [comment]
@Theodlz Should we fix this one here or open another PR?

**Comment by mcoughlin** [comment]
We got this one in a separate PR.

**Pull request closed without merging**
