### PR TITLE
Require typing-extensions>=4.0.1

### PR DESCRIPTION
**Pull request by acrellin**

### CODE REVIEW

**Comment by stefanv** [comment]
Do we use typing extensions? I don't think we're running mypy in our CI.

**Comment by acrellin** [comment]
@stefanv I think it's `astropy` v5.0 that requires it.

**Comment by stefanv** [comment]
So won't it come in automatically via astropy then?

**Comment by acrellin** [comment]
@stefanv apparently astropy doesn't correctly specify the minimum required version of typing-extensions; if you have 3.x installed, you'll just see an error. Manually installing 4.x resolves it.

**Comment by stefanv** [comment]
OK, please add a comment above that line explaining, then go ahead and merge.
(AFAIK `requirements.txt` respects `#` comments, and we should get in the habit of doing so for all strange cases).

**Comment by stefanv** [comment]
Perfect, thanks!

**Pull request merged**
