### PR TITLE
Source page plot enhancements

### PR DESCRIPTION
**Pull request by kmshin1397**
Minor improvements to the centroid plot and the HR diagram on the Source page:
- Both now adjust text color (for axis labels, title, etc) based on light/dark theme
- HR diagram sizing better adjusts to screen width to prevent overflow on mobile devices

Before:
image
image

After:
Screenshot 2021-07-29 141011
Screenshot 2021-07-29 142417

### CODE REVIEW

**Review by dmitryduev — APPROVED** [review]
Thank you very much for this @kmshin1397! Would you mind mirroring the offset plot part in a Fritz PR?

**Comment by kmshin1397** [comment]
> Thank you very much for this @kmshin1397! Would you mind mirroring the offset plot part in a Fritz PR?

Yup, coming up shortly :)

**Review by guynir42 — APPROVED** [review]

**Comment by dmitryduev** [comment]
@kmshin1397 CI failure seems relevant:
```
FAIL: skyportal/tests/frontend/sources_and_followup_etc/test_sources.py:459 in test_centroid_plot
```
mind taking a look?

**Review by dmitryduev — APPROVED** [review]
CI failure unrelated, merging.

**Pull request merged**
