### PR TITLE
Make source and plot handlers async

### PR DESCRIPTION
**Pull request by bfhealy**
This PR makes certain functions in source.py and plot.py asynchronous to address timeout issues. The modified code currently raises the following errors locally:

Screen Shot 2022-12-21 at 3 56 37 PM
Screen Shot 2022-12-21 at 3 56 16 PM

I welcome comments on which additional functions to make asynchronous and how to avoid the above errors.

### CODE REVIEW

**Comment by mcoughlin** [comment]
@bfhealy There is the await calls in the front-end for that.

**Comment by bfhealy** [comment]
@mcoughlin The latest push attempts to use await in GroupSources.jsx, but it doesn't seem quite right. The previous errors no longer appear, but the group sources page hangs without displaying any sources.

**Comment by mcoughlin** [comment]
@bfhealy looks like the GCN tests are relevant?

**Comment by bfhealy** [comment]
@mcoughlin Those tests could be relevant, I'll take a look.

**Comment by bfhealy** [comment]
@mcoughlin The GCN tests are passing now; I think the remaining failures are not related to these changes.

**Pull request merged**
