### PR TITLE
Add reset specs button for spectroscopy plot

### LINKED ISSUE #2703: Clear all button for the spectroscopic panel

### PR DESCRIPTION
**Pull request by jadalilleboe**
Adds a button to reset specs on spectroscopy plot: 
resetgif
I'm not sure where to add a test for this, I can't find any frontend tests for the bokeh plots
Closes #2703

### CODE REVIEW

**Comment by stefanv** [comment]
Thanks @jadalilleboe! The button takes up a lot of real estate.  Can we make it small, put it under the select-boxes, and perhaps give it a more explanatory name? Even just "Reset" would work if it were rendered under the checkboxes.

**Comment by jadalilleboe** [comment]
@stefanv how does this look?
Screenshot (37)

**Comment by stefanv** [comment]
Nice, thank you! We can merge this for now, and if we want to later replace it with a little reset icon.

**Review by mcoughlin — APPROVED** [review]
Looks nice. Thanks for the work @jadalilleboe and the comments @stefanv.

**Pull request merged**
