### PR TITLE
Dark Mode Colors

### LINKED ISSUE #1305: Improve app color palette/dark mode
There are likely pages throughout the app where dark mode does not look as it should or just doesn't look good. Exploring enhancements to the overall color theme (i.e. a darker blue for the header?) would be good to do in conjunction. Potentially could expose the color theme to the configs as well.

### PR DESCRIPTION
**Pull request by joelachance**
Updates to the dark mode colors palette. This partially addresses #1305.

### CODE REVIEW

**Comment by kmshin1397** [comment]
@joelachance Is this different from #1632?

**Comment by joelachance** [comment]
@kmshin1397 hello, this is the same PR. As I was looking at the other PR and trying to make the CI/CD pass, there were a lot of issues that kept coming up from changes I hadn't made, so it made sense to do some cherry-picking and start fresh.

I'm not sure why the tests aren't passing, but it does seem like we're getting closer. Any clue why tests might not be passing?

Working on the QuickSearchBar to make the changes discussed in the other PR. I'll close that one and we can work off of this one.

**Comment by kmshin1397** [comment]
@joelachance Got ya. I suspect the tests are failing due to the `gray` not existing error we discussed in the other PR. I think the failing tests are all on page that would fail to render due to that color not being available.

**Comment by joelachance** [comment]
@kmshin1397 I relaced any `theme.palette.gray`'s with `grey` and import `grey` from MUI directly. I'm still getting some errors, have you seen any of these before?

```=========================== short test summary info ============================
FAILED skyportal/tests/frontend/test_followup_requests.py::test_delete_followup_request_IOI
FAILED skyportal/tests/frontend/test_followup_requests.py::test_submit_new_followup_request_SPRAT
FAILED skyportal/tests/frontend/test_followup_requests.py::test_submit_new_followup_request_IOO
FAILED skyportal/tests/frontend/test_followup_requests.py::test_delete_followup_request_SPRAT
FAILED skyportal/tests/frontend/test_followup_requests.py::test_delete_followup_request_IOO
FAILED skyportal/tests/frontend/test_followup_requests.py::test_submit_new_followup_request_IOI
= 6 failed, 351 passed, 3 xfailed, 1 xpassed, 562 warnings, 12 rerun in 2217.15s (0:36:57) =
Traceback (most recent call last):
  File "baselayer/tools/junitxml_report.py", line 56, in <module>
    filename = test['@file']
KeyError: '@file'
baselayer/Makefile:144: recipe for target 'test_report' failed
[16:19:49 test_frontend] Initializing test database
  Config files: baselayer/config.yaml.defaults
                config.yaml.defaults
                test_config.yaml
Dropping tables on database skyportal_test
Creating tables on database skyportal_test
Refreshed tables:
 - acls
 - roles
 - role_acls
 - users
 - user_acls
 - tokens
 - token_acls
 - user_roles
 - usersocialauths
 - nonces
 - associations
 - codes
 - partials

[16:19:49 test_frontend] Waiting for server to appear at http://localhost:5000...
[16:20:20 test_frontend] Launching pytest on skyportal/tests/api skyportal/tests/frontend skyportal/tests/tools skyportal/tests/utils...

[16:57:24 test_frontend] Terminating supervisord...
[16:57:24 test_frontend] Test run failed
make: *** [test_report] Error 1
Makefile:74: recipe for target 'run_testing' failed
make: *** [run_testing] Terminated
```

**Comment by kmshin1397** [comment]
@joelachance Ah right, I would not worry about those. Those requests rely on getting a response from an external API (the LT telescope) so those can sometimes fail if the LT server is being unresponsive for whatever reason.

**Comment by acrellin** [comment]
Looking great! Autoannotations section on source page needs some CSS love -- should we do that here or in another PR?

**Comment by stefanv** [comment]
I didn't want to touch that here, because Joe is working on another PR.

**Review by acrellin — APPROVED** [review]
I think I prefer the existing color palette over this one a bit, but it's a minor personal preference, and I'm good with this going in. THanks @joelachance

**Comment by acrellin** [comment]
I updated the PR description so that it won't completely close the linked issue, as there are still areas that need to be massaged in dark mode (e.g. autoannotations on source page)

**Comment by joelachance** [comment]
I'm happy to just address them here. I'm still finding spots where we can make some improvements, so while I don't want to drag this out longer, I think it makes sense to just wrap it all together into a single PR. 
Also, thanks for the feedback about the colors too @acrellin! I'm definitely open to new suggestions, and at the least I'd like to improve this current palette to work a bit better in both light and dark.

**Comment by acrellin** [comment]
@joelachance I think it looks good as-is; we can always iterate on it further if needed. Thanks a lot for the great work!

**Comment by joelachance** [comment]
Ready for a re-review. A couple of things:

1. I updated the items for both RecentSources and TopSources. The quick view button still gets a bit squished when the browser width gets narrower, but things move around a bit less now. Updated some colors here so it'll look a bit better in light & dark mode (opening ticket for the error shown here as well):
Screen Shot 2021-03-01 at 8 13 37 AM

2. I played around with updating Auto-annotations @acrellin. It looks like we're using mui-datatables for this one, which is why our default theme doesn't update this component (we've wrapped this component in its own Mui theme). We can merge the default theme with the theme we wrap auto-annotations with, but there's some props we then need to expose to the application to do this (namely, `disableTransitions` from `Theme.jsx`). It looks like we're only using this for testing (I'm making this assumption from `Main.jsx.template`, LOC `93`:
```
<Theme {% if testing %} disableTransitions {% endif %}>
```
I don't know if we need this? If we can remove it I think we can fix the auto-annotations table.
Another suggestion would be to not use mui-datatables, but I'm assuming we had a good reason to use these initially, and migrating these to whatever MUI uses is probably more work than it's worth.
There's also other graphs that don't respect dark mode on this page that I didn't address.

3. Last, I'm going to continue looking at some colors. I think we should tweak the secondary color, as its contrast could be a bit better in both themes. Looking at some of these options, FYI. Right now I like some version of the darker one in #3:
Screen Shot 2021-03-01 at 8 17 15 AM

**Comment by acrellin** [comment]
@joelachance excellent, this looks great. Regarding the theme & autoannotations mui-datatable, yes I think we can remove `disableTransitions` now, especially if it'll help here (that was supposed to make selenium tests less flaky, but I'm not sure if it had an impact)

**Comment by stefanv** [comment]
The transitions were disabled to ensure that we didn't run into any troubles during testing with objects fading in and out or moving about.

Why can we not fix the auto-annotations without removing that segment?

**Comment by kmshin1397** [comment]
@joelachance Have you tried doing something like [this](https://github.com/skyportal/skyportal/blob/e31d670b105b1b1126cf671464a5dfc42bbb81e8/static/js/components/TokenList.jsx#L30) (`TokenList.jsx`) in the `createMuiTheme` in the `ObjPageAnnotations.jsx`? That seemed to fix the palette/dark mode issue for me in other MUI DataTables

**Comment by joelachance** [comment]
@kmshin1397 That works :) Good solution!
I made some small tweaks to the color palette, fixed the oblong shape of the Notifications icon in the header, and updated a couple of colors along the way. Should be ready for another review. Thanks everyone!

**Review by acrellin — APPROVED** [review]
Looks great, thanks @joelachance !
Only thing that stands out to me is MUI Button components (in dark mode, they're big and bright), but I'm not sure what's possible there, and that can wait for a future PR

**Comment by stefanv** [comment]
This looks very nice, thank you Joe!

Some smaller things I've noticed:

- the title of the source is quite hidden, with the icons around it bright; perhaps that should be switched?
- the search bar results are very hard to read
- survey buttons look... greenish, maybe just an optical illusion :)  But should probably be styled using Button
- plots are not styled (we may have to do this in another PR; it's likely a bit more involved); this includes vega plots, which have transparent backgrounds but should use light axis text in dark mode

**Comment by joelachance** [comment]
@acrellin , which button components are you looking at? I'm sure we can do something...

@stefanv , good callouts! Below are some screenshots, the top three are updated. As far as the Bokeh plots, I think that's a future PR. Right now it seems we might need to add that to the API request and do color changes on the Bokeh side (I'm hoping this is possible?), I don't think anything we give it on the front end will do a good job here.

Screen Shot 2021-03-03 at 11 04 44 PM
Screen Shot 2021-03-03 at 11 04 18 PM
Screen Shot 2021-03-03 at 11 00 17 PM
Screen Shot 2021-03-03 at 11 00 30 PM
Screen Shot 2021-03-03 at 11 04 04 PM
Screen Shot 2021-03-03 at 11 04 09 PM

**Comment by stefanv** [comment]
Yes, beautiful!!

**Review by stefanv — APPROVED** [review]

**Comment by stefanv** [comment]
@joelachance This is looking absolutely great :rocket:  If you have some wisdom to share after your styling adventures, a paragraph or two in the styling guide would be welcome (but I think this PR is good to go).

**Review by kmshin1397 — CHANGES_REQUESTED** [review]
This looks really good, thanks @joelachance! The two failures on the CI run are real but should be a simple fix. You will need to update the xpaths used in `test_recent_sources.py` to reflect the change you made to the source link. Basically, you just need to replace the `a` with `span` on [this line](https://github.com/skyportal/skyportal/blob/383ae98234d503d356cb97fa471150a925171fd3/skyportal/tests/frontend/test_recent_sources.py#L40) and the same thing with the other two tests in that file. Once you get that in, we can merge this :)

**Comment by acrellin** [comment]
@joelachance  The buttons I was referring to are the MUI buttons throughout the app which stand out in dark mode, e.g. here on the source page: 
image

As opposed to something like what the Dark Reader browser extension does here:
image

**Comment by acrellin** [comment]
I'm happy with this as-is, though -- let's get this in today and do any further refinements in another PR

**Review by kmshin1397 — APPROVED** [review]

**Comment by kmshin1397** [comment]
Finally green! Merging now

**Comment by stefanv** [comment]
NICE! Thanks Joe!

**Comment by joelachance** [comment]
Thanks guys!

@acrellin, do you think those buttons should be darker? We can make them that primary blue you see in the title, if people think that would look better.

**Pull request merged**
