### PR TITLE
Remove ..._exists flags when fetching multiple sources

### PR DESCRIPTION
**Pull request by Theodlz**
An attempt to fix or at least understand where the performance issues come from when querying list of sources. It seems not to come from querying the sources itself, but all the subqueries we run for each source. At least, this is what appears when running it locally on a small database.

There are many more subqueries, so this might not be enough of course, but worth trying.

### CODE REVIEW

**Review by mcoughlin — COMMENTED** [review]
@Theodlz I suspect Dan and AMPEL are the main folks who might use this. Maybe check with them quick?

**Comment by Theodlz** [comment]
I'm trying to fix the react memo stuff, looks like rerendering triggers another API call from the VEGA plots. There was no memo for the photometry which was already an issue, but adding it doesnt seem to fix that. Once fixed, we can merge and try that on preview to see how the performance changes.

**Comment by Theodlz** [comment]
> @Theodlz I suspect Dan and AMPEL are the main folks who might use this. Maybe check with them quick?

Of course. This is mostly to assess performance. If it does prove useful on preview, then I'll ask around.

**Review by mcoughlin — APPROVED** [review]
I am ok with giving it a try then!

**Comment by Theodlz** [comment]
Merging so we can try it on preview. Will revert if needed.

**Pull request merged**
