### PR TITLE
Allow adding users to new groups from user management page

### PR DESCRIPTION
**Pull request by acrellin**
Partially addresses https://github.com/skyportal/skyportal/issues/914 
add_user_to_groups_from_user_mgmt_pg

### CODE REVIEW

**Review by dmitryduev — CHANGES_REQUESTED** [review]
Looks good! Two minor comments:
- Please add some padding above the SUBMIT button
- remove single-user groups from the options

**Comment by acrellin** [comment]
@dmitryduev good catch -- done! See new screen capture:
add_user_to_groups_from_user_mgmt_pg
Ready for re-review

**Review by dannygoldstein — APPROVED** [review]

**Review by dmitryduev — APPROVED** [review]
👍

**Comment by dannygoldstein** [comment]
Merging as failures are unrelated and travis is not spinning up on any PRs for some reason

**Pull request merged**
