### PR TITLE
Accordianify the GcnEventPage

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR uses  Accordian on the GCN Event page to make it similar to the rest of the app.

image

### CODE REVIEW

**Review by guynir42 — APPROVED** [review]
LGTM

**Comment by mcoughlin** [comment]
@guynir42 Good with one review or want a second one?

**Comment by guynir42** [comment]
@mcoughlin If it looks ok on your local machine I think this is good to merge.

**Comment by mcoughlin** [comment]
Yes it does! Can you merge it @guynir42 ?

**Comment by guynir42** [comment]
@mcoughlin I will merge after we finish deploying.

**Comment by mcoughlin** [comment]
Ok! Good luck!

**Pull request merged**
