### PR TITLE
Highlight selected sidebar menu item.

### PR DESCRIPTION
**Pull request by stefanv**
Peek 2020-09-03 02-30

### CODE REVIEW

**Review by kmshin1397 — APPROVED** [review]

**Comment by acrellin** [comment]
Nice!

**Comment by dmitryduev** [comment]
The tests are known to be flaky, right? Shall we mark them xfail for now?

**Comment by acrellin** [comment]
The same two tests are failing on both Travis and GA here; makes me hesitant to merge without seeing if they're actually related to the changes here.

**Comment by acrellin** [comment]
I'll restart the builds and see if the failures persist.

**Comment by stefanv** [comment]
Failed locally:

```
FAILED skyportal/tests/frontend/test_top_sources.py::test_top_sources - selenium.common.exceptions.TimeoutException: Message:
FAILED skyportal/tests/frontend/test_frontpage.py::test_foldable_sidebar - selenium.common.exceptions.TimeoutException: Message:
```

**Comment by stefanv** [comment]
Test fixed.

**Comment by stefanv** [comment]
Top sources and newsfeed failures.

**Pull request merged**
