### PR TITLE
fix Photometry.PUT with groups='all'

### LINKED ISSUE #1263: PUT /api/photometry doesn't accept group_ids="all"
In 92a46ae803472caea04b4f69d5f74b3129048cae as deployed on https://fritz.science, PUT /api/photometry with the following payload:

```
{"obj_id": "ZTF20aciudrr", "group_ids": "all", "magsys": "ab", "instrument_id": 1, "filter": ["ztfr", "ztfg", "ztfr", "ztfg", "ztfr", "ztfg", "ztfr", "ztfg", "ztfr", "ztfr", "ztfg", "ztfg", "ztfr", "ztfg", "ztfg", "ztfr", "ztfr", "ztfr", "ztfg", "ztfr", "ztfg", "ztfg", "ztfr"], "mjd": [59130.53195599979, 59135.473286999855, 59135.51195599977, 59137.47579859989, 59137.51334490022, 59139.45453700004, 59139.51506939996, 59141.474490699824, 59141.51422449993, 59143.48528939998, 59143.50987270009, 59145.46446759999, 59145.50555559993, 59149.50347220013, 59150.50871529989, 59150.52805559989, 59151.52115740022, 59152.4833217999, 59152.516307900194, 59155.50021990016, 59155.5080093001, 59156.4847916998, 59156.53829859989], "limiting_mag": [19.67770004272461, 20.11709976196289, 20.059200286865234, 20.281099319458008, 20.224000930786133, 19.809099197387695, 20.236799240112305, 20.57659912109375, 20.31290054321289, 20.414499282836914, 20.680700302124023, 20.57069969177246, 20.48349952697754, 20.242000579833984, 20.642900466918945, 20.029699325561523, 20.11090087890625, 19.808948516845703, 19.819171905517578, 19.9112606048584, 19.913991928100586, 19.600677490234375, 20.005773544311523], "mag": [null, 19.239099502563477, 19.426000595092773, 19.11280059814453, 19.24570083618164, 19.024700164794922, 19.09149932861328, 18.876699447631836, 18.914199829101562, 18.901599884033203, 18.915199279785156, 18.84280014038086, 18.89069938659668, 18.89459991455078, 18.92799949645996, 18.957399368286133, 18.848100662231445, 18.882665634155273, 18.993907928466797, 19.110898971557617, 19.127714157104492, 19.466022491455078, 19.24942970275879], "magerr": [null, 0.1391019970178604, 0.13817599415779114, 0.12731100618839264, 0.11334399878978729, 0.1459749937057495, 0.11234399676322937, 0.11080300062894821, 0.09862300008535385, 0.0836310014128685, 0.1064319983124733, 0.08669500052928925, 0.09344000369310379, 0.10920300334692001, 0.13083499670028687, 0.11362800002098083, 0.08791899681091309, 0.1066831648349762, 0.13501590490341187, 0.10501029342412949, 0.14216870069503784, 0.19518424570560455, 0.12731821835041046], "ra": [null, 134.5934039, 134.5934169, 134.5933773, 134.593404, 134.593372, 134.5933825, 134.5933984, 134.5933945, 134.5933917, 134.5933988, 134.5933848, 134.5933991, 134.5933909, 134.5934048, 134.5934296, 134.5934341, 134.593388, 134.5933606, 134.5933857, 134.5933939, 134.5933847, 134.5933954], "dec": [null, 15.0412865, 15.041256, 15.0412686, 15.0412482, 15.0412709, 15.0412572, 15.0412656, 15.0412765, 15.0412744, 15.0412673, 15.041271, 15.0412726, 15.0413061, 15.0412751, 15.041267, 15.0412856, 15.0412655, 15.0412913, 15.0412952, 15.0412737, 15.0411913, 15.0412605]}
```

raises:

```
(psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "a"
LINE 3: WHERE groups.id IN (41, 'a', 'l', 63)
                                ^

[SQL: SELECT groups.id AS groups_id, groups.created_at AS groups_created_at, groups.modified AS groups_modified, groups.name AS groups_name, groups.nickname AS groups_nickname, groups.single_user_group AS groups_single_user_group 
FROM groups 
WHERE groups.id IN (%(id_1)s, %(id_2)s, %(id_3)s, %(id_4)s)]
[parameters: {'id_1': 41, 'id_2': 'a', 'id_3': 'l', 'id_4': 63}]
(Background on this error at: http://sqlalche.me/e/9h9h)
```

That looks like it's falling into the list/tuple case in `PhotometryHandler.get_group_ids()`, but I have no idea how.

### PR DESCRIPTION
**Pull request by dannygoldstein**
@jvansanten

Fixes #1263.

There was a bug in the Photometry handler where `group_ids = all` was not properly being left as a string instead of being translated into a list containing, at minimum, the id of the sitewide group. This produced an error like

```
(psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "a"
LINE 3: WHERE groups.id IN (41, 'a', 'l', 63)
                                ^

[SQL: SELECT groups.id AS groups_id, groups.created_at AS groups_created_at, groups.modified AS groups_modified, groups.name AS groups_name, groups.nickname AS groups_nickname, groups.single_user_group AS groups_single_user_group 
FROM groups 
WHERE groups.id IN (%(id_1)s, %(id_2)s, %(id_3)s, %(id_4)s)]
[parameters: {'id_1': 41, 'id_2': 'a', 'id_3': 'l', 'id_4': 63}]
(Background on this error at: http://sqlalche.me/e/9h9h)
```

as seen in #1263. 

The condition to reproduce this error is to POST photometry to some numeric group_ids, then attempt to PUT the photometry with `group_ids='all'`. 

I added a test to reproduce this error. It reproduces the error when run without the fixes to the photometry handler implemented in this PR. The fixes in this PR allow the test to pass.

### CODE REVIEW

**Comment by dannygoldstein** [comment]
Ready for review

**Review by dmitryduev — APPROVED** [review]
LGTM!

**Review by acrellin — APPROVED** [review]

**Review by stefanv — APPROVED** [review]

**Comment by dannygoldstein** [comment]
fixed merge conflicts

**Comment by dannygoldstein** [comment]
failures unrelated, ready for merge

**Pull request merged**
