### PR TITLE
Task 1 Sort by default date saved most recent

### PR DESCRIPTION
**Pull request by laurall974**
We modify source.py and replace order_by = none by saved_at desc.

### CODE REVIEW

**Comment by mcoughlin** [comment]
@laurall974 Looks like you didn't lint the code:

pre-commit install 
pre-commit run --files skyportal/handlers/api/source.py
git commit skyportal/handlers/api/source.py

**Comment by Theodlz** [comment]
Its a necessary step to follow before you commit anything. You run the install just once of course, but then you always run `pre-commit run --file <youfileswithspacesbetweenthem>`.
The linter will automatically fix your files format. However, sometimes (especially on the frontend) it will tell you that you coded something in a way that is not recommended. If thats the case you need to changed your code manually, then retry linting your files.
Do this until no errors appear anymore.
Then you can git add and git commit as usual.

**Comment by Theodlz** [comment]
Hi @laurall974. I will be able to review your PR tomorrow. Therefore if you are able to today, please lint the files you modified so I can review the PR :)

**Comment by laurall974** [comment]
> 

Hi @Theodlz ,
therefor should I close my PR and create another one ?

**Comment by Theodlz** [comment]
Not at all (did I say that? Hahaha)

You just need to lint your files and re commit them.

The linting process I mandatory and its goal is to clearly format your files. We gave you the commands to run above. Nothing says that you should close that PR in any way.

You just need to lint, git add commit push as usual (you just do the linting before anything else)

**Comment by laurall974** [comment]
> Not at all (did I say that? Hahaha)
> 
> You just need to lint your files and re commit them.
> 
> The linting process I mandatory and its goal is to clearly format your files. We gave you the commands to run above. Nothing says that you should close that PR in any way.
> 
> You just need to lint, git add commit push as usual (you just do the linting before anything else)

I dit it ! Is it ok ?

**Comment by laurall974** [comment]
> @laurall974 I dont see the update here or on your branch.

Is it ok now @mcoughlin ?

**Comment by mcoughlin** [comment]
@laurall974 Best way to see is if it doesn't break any (non-flaky) tests! So must wait about ~40 minutes and see.

**Review by mcoughlin — APPROVED** [review]
LGTM

**Pull request merged**
