### PR TITLE
Addresses various errors (components becoming controlled, etc.)

### PR DESCRIPTION
**Pull request by stefanv**
Fixes gh-834

### CODE REVIEW

**Comment by acrellin** [comment]
@stefanv looks like a mapped list in Group.jsx also needs some key props (from that linked issue)

**Comment by stefanv** [comment]
@acrellin I could not reproduce that error; can you?

**Comment by stefanv** [comment]
Upload photometry seems to be the culprit in both failures.  Is this a known issue?

**Comment by acrellin** [comment]
> Upload photometry seems to be the culprit in both failures. Is this a known issue?

@stefanv yes this is failing on master on the #838 merge commit (https://github.com/skyportal/skyportal/runs/1070989155 and https://travis-ci.org/github/skyportal/skyportal/builds/724075078#L4407)

**Comment by acrellin** [comment]
Merging. Only test failures here are also present on master, at least since https://github.com/skyportal/skyportal/commit/0b4334102d0666b0eb95313c29d42e0c117e3324

**Pull request merged**
