### PR TITLE
Distinguish between comments posted by logged-in users & bots; allow excluding bot comments from newsfeed

### PR DESCRIPTION
**Pull request by acrellin**
newsfeed_bot_comments

Closes https://github.com/skyportal/skyportal/issues/2075

### CODE REVIEW

**Review by dmitryduev — APPROVED** [review]
Looks great!

**Review by kmshin1397 — COMMENTED** [review]
Looks good thanks @acrellin! The one comment I have is that perhaps it would be good to document the criteria for a bot comment (token-based) somewhere the end user could see it. Maybe a tooltip in the news feed preferences? Or just an update to the docstrings for posting comments so it shows up in the API docs? Right now I think that's only clear if you read the code or the data model definition.

**Comment by acrellin** [comment]
@kmshin1397 Done: 
bot_comments_tooltip

**Review by kmshin1397 — APPROVED** [review]
Looks good, thanks! I'll merge once the CI finishes running

**Pull request merged**
