### PR TITLE
Update GCN notice types enum

### PR DESCRIPTION
**Pull request by kmshin1397**
I think an update to the `pygcn` library added a value to the GCN notice types, leading to a mismatch in the ENUM values between migrated databases and newly created ones using the new gcn package version. Example migration CI test failure: https://github.com/skyportal/skyportal/pull/2136/checks?check_run_id=3147246654

### CODE REVIEW

**Comment by mcoughlin** [comment]
@kmshin1397 I see the below in the migration... do you understand enough to translate?

alter type "public"."noticetype" rename to "noticetype__old_version_to_be_dropped";

create type "public"."noticetype" as enum ('GRB_COORDS', 'TEST_COORDS', 'IM_ALIVE', 'KILL_SOCKET', 'MAXBC', 'BRAD_COORDS', 'GRB_FINAL', 'HUNTS_SRC', 'ALEXIS_SRC', 'XTE_PCA_ALERT', 'XTE_PCA_SRC', 'XTE_ASM_ALERT', 'XTE_ASM_SRC', 'COMPTEL_SRC', 'IPN_RAW', 'IPN_SEG', 'SAX_WFC_ALERT', 'SAX_WFC_SRC', 'SAX_NFI_ALERT', 'SAX_NFI_SRC', 'XTE_ASM_TRANS', 'spare38', 'IPN_POS', 'HETE_ALERT_SRC', 'HETE_UPDATE_SRC', 'HETE_FINAL_SRC', 'HETE_GNDANA_SRC', 'HETE_TEST', 'GRB_CNTRPART', 'SWIFT_TOO_FOM', 'SWIFT_TOO_SC_SLEW', 'DOW_TOD', 'spare50', 'INTEGRAL_POINTDIR', 'INTEGRAL_SPIACS', 'INTEGRAL_WAKEUP', 'INTEGRAL_REFINED', 'INTEGRAL_OFFLINE', 'INTEGRAL_WEAK', 'AAVSO', 'MILAGRO_POS', 'KONUS_LC', 'SWIFT_BAT_GRB_ALERT', 'SWIFT_BAT_GRB_POS_ACK', 'SWIFT_BAT_GRB_POS_NACK', 'SWIFT_BAT_GRB_LC', 'SWIFT_BAT_SCALEDMAP', 'SWIFT_FOM_OBS', 'SWIFT_SC_SLEW', 'SWIFT_XRT_POSITION', 'SWIFT_XRT_SPECTRUM', 'SWIFT_XRT_IMAGE', 'SWIFT_XRT_LC', 'SWIFT_XRT_CENTROID', 'SWIFT_UVOT_DBURST', 'SWIFT_UVOT_FCHART', 'SWIFT_BAT_GRB_LC_PROC', 'SWIFT_XRT_SPECTRUM_PROC', 'SWIFT_XRT_IMAGE_PROC', 'SWIFT_UVOT_DBURST_PROC', 'SWIFT_UVOT_FCHART_PROC', 'SWIFT_UVOT_POS', 'SWIFT_BAT_GRB_POS_TEST', 'SWIFT_POINTDIR', 'SWIFT_BAT_TRANS', 'SWIFT_XRT_THRESHPIX', 'SWIFT_XRT_THRESHPIX_PROC', 'SWIFT_XRT_SPER', 'SWIFT_XRT_SPER_PROC', 'SWIFT_UVOT_POS_NACK', 'SWIFT_BAT_ALARM_SHORT', 'SWIFT_BAT_ALARM_LONG', 'SWIFT_UVOT_EMERGENCY', 'SWIFT_XRT_EMERGENCY', 'SWIFT_FOM_PPT_ARG_ERR', 'SWIFT_FOM_SAFE_POINT', 'SWIFT_FOM_SLEW_ABORT', 'SWIFT_BAT_QL_POS', 'SWIFT_BAT_SUB_THRESHOLD', 'SWIFT_BAT_SLEW_POS', 'AGILE_GRB_WAKEUP', 'AGILE_GRB_GROUND', 'AGILE_GRB_REFINED', 'SWIFT_ACTUAL_POINTDIR', 'AGILE_MCAL_ALERT', 'AGILE_POINTDIR', 'AGILE_TRANS', 'AGILE_GRB_POS_TEST', 'FERMI_GBM_ALERT', 'FERMI_GBM_FLT_POS', 'FERMI_GBM_GND_POS', 'FERMI_GBM_LC', 'FERMI_GBM_GND_INTERNAL', 'FERMI_GBM_FIN_POS', 'FERMI_GBM_ALERT_INTERNAL', 'FERMI_GBM_FLT_INTERNAL', 'FERMI_GBM_TRANS', 'FERMI_GBM_POS_TEST', 'FERMI_LAT_POS_INI', 'FERMI_LAT_POS_UPD', 'FERMI_LAT_POS_DIAG', 'FERMI_LAT_TRANS', 'FERMI_LAT_POS_TEST', 'FERMI_LAT_MONITOR', 'FERMI_SC_SLEW', 'FERMI_LAT_GND', 'FERMI_LAT_OFFLINE', 'FERMI_POINTDIR', 'SIMBADNED', 'FERMI_GBM_SUBTHRESH', 'SWIFT_BAT_MONITOR', 'MAXI_UNKNOWN', 'MAXI_KNOWN', 'MAXI_TEST', 'OGLE', 'CBAT', 'MOA', 'SWIFT_BAT_SUBSUB', 'SWIFT_BAT_KNOWN_SRC', 'VOE_11_IM_ALIVE', 'VOE_20_IM_ALIVE', 'FERMI_SC_SLEW_INTERNAL', 'COINCIDENCE', 'FERMI_GBM_FIN_INTERNAL', 'SUZAKU_LC', 'SNEWS', 'LVC_PRELIMINARY', 'LVC_INITIAL', 'LVC_UPDATE', 'LVC_TEST', 'LVC_COUNTERPART', 'AMON_ICECUBE_COINC', 'AMON_ICECUBE_HESE', 'CALET_GBM_FLT_LC', 'CALET_GBM_GND_LC', 'LVC_EARLY_WARNING', 'LVC_RETRACTION', 'GWHEN_COINC', 'AMON_ICECUBE_EHE', 'HAWC_BURST_MONITOR', 'AMON_NU_EM_COINC', 'ICECUBE_ASTROTRACK_GOLD', 'ICECUBE_ASTROTRACK_BRONZE', 'SK_SN', 'ICECUBE_CASCADE');

alter table "public"."gcnnotices" alter column notice_type type "public"."noticetype" using notice_type::text::"public"."noticetype";

drop type "public"."noticetype__old_version_to_be_dropped";

**Comment by kmshin1397** [comment]
> @kmshin1397 I see the below in the migration... do you understand enough to translate?
> 
> alter type "public"."noticetype" rename to "noticetype__old_version_to_be_dropped";
> 
> create type "public"."noticetype" as enum ('GRB_COORDS', 'TEST_COORDS', 'IM_ALIVE', 'KILL_SOCKET', 'MAXBC', 'BRAD_COORDS', 'GRB_FINAL', 'HUNTS_SRC', 'ALEXIS_SRC', 'XTE_PCA_ALERT', 'XTE_PCA_SRC', 'XTE_ASM_ALERT', 'XTE_ASM_SRC', 'COMPTEL_SRC', 'IPN_RAW', 'IPN_SEG', 'SAX_WFC_ALERT', 'SAX_WFC_SRC', 'SAX_NFI_ALERT', 'SAX_NFI_SRC', 'XTE_ASM_TRANS', 'spare38', 'IPN_POS', 'HETE_ALERT_SRC', 'HETE_UPDATE_SRC', 'HETE_FINAL_SRC', 'HETE_GNDANA_SRC', 'HETE_TEST', 'GRB_CNTRPART', 'SWIFT_TOO_FOM', 'SWIFT_TOO_SC_SLEW', 'DOW_TOD', 'spare50', 'INTEGRAL_POINTDIR', 'INTEGRAL_SPIACS', 'INTEGRAL_WAKEUP', 'INTEGRAL_REFINED', 'INTEGRAL_OFFLINE', 'INTEGRAL_WEAK', 'AAVSO', 'MILAGRO_POS', 'KONUS_LC', 'SWIFT_BAT_GRB_ALERT', 'SWIFT_BAT_GRB_POS_ACK', 'SWIFT_BAT_GRB_POS_NACK', 'SWIFT_BAT_GRB_LC', 'SWIFT_BAT_SCALEDMAP', 'SWIFT_FOM_OBS', 'SWIFT_SC_SLEW', 'SWIFT_XRT_POSITION', 'SWIFT_XRT_SPECTRUM', 'SWIFT_XRT_IMAGE', 'SWIFT_XRT_LC', 'SWIFT_XRT_CENTROID', 'SWIFT_UVOT_DBURST', 'SWIFT_UVOT_FCHART', 'SWIFT_BAT_GRB_LC_PROC', 'SWIFT_XRT_SPECTRUM_PROC', 'SWIFT_XRT_IMAGE_PROC', 'SWIFT_UVOT_DBURST_PROC', 'SWIFT_UVOT_FCHART_PROC', 'SWIFT_UVOT_POS', 'SWIFT_BAT_GRB_POS_TEST', 'SWIFT_POINTDIR', 'SWIFT_BAT_TRANS', 'SWIFT_XRT_THRESHPIX', 'SWIFT_XRT_THRESHPIX_PROC', 'SWIFT_XRT_SPER', 'SWIFT_XRT_SPER_PROC', 'SWIFT_UVOT_POS_NACK', 'SWIFT_BAT_ALARM_SHORT', 'SWIFT_BAT_ALARM_LONG', 'SWIFT_UVOT_EMERGENCY', 'SWIFT_XRT_EMERGENCY', 'SWIFT_FOM_PPT_ARG_ERR', 'SWIFT_FOM_SAFE_POINT', 'SWIFT_FOM_SLEW_ABORT', 'SWIFT_BAT_QL_POS', 'SWIFT_BAT_SUB_THRESHOLD', 'SWIFT_BAT_SLEW_POS', 'AGILE_GRB_WAKEUP', 'AGILE_GRB_GROUND', 'AGILE_GRB_REFINED', 'SWIFT_ACTUAL_POINTDIR', 'AGILE_MCAL_ALERT', 'AGILE_POINTDIR', 'AGILE_TRANS', 'AGILE_GRB_POS_TEST', 'FERMI_GBM_ALERT', 'FERMI_GBM_FLT_POS', 'FERMI_GBM_GND_POS', 'FERMI_GBM_LC', 'FERMI_GBM_GND_INTERNAL', 'FERMI_GBM_FIN_POS', 'FERMI_GBM_ALERT_INTERNAL', 'FERMI_GBM_FLT_INTERNAL', 'FERMI_GBM_TRANS', 'FERMI_GBM_POS_TEST', 'FERMI_LAT_POS_INI', 'FERMI_LAT_POS_UPD', 'FERMI_LAT_POS_DIAG', 'FERMI_LAT_TRANS', 'FERMI_LAT_POS_TEST', 'FERMI_LAT_MONITOR', 'FERMI_SC_SLEW', 'FERMI_LAT_GND', 'FERMI_LAT_OFFLINE', 'FERMI_POINTDIR', 'SIMBADNED', 'FERMI_GBM_SUBTHRESH', 'SWIFT_BAT_MONITOR', 'MAXI_UNKNOWN', 'MAXI_KNOWN', 'MAXI_TEST', 'OGLE', 'CBAT', 'MOA', 'SWIFT_BAT_SUBSUB', 'SWIFT_BAT_KNOWN_SRC', 'VOE_11_IM_ALIVE', 'VOE_20_IM_ALIVE', 'FERMI_SC_SLEW_INTERNAL', 'COINCIDENCE', 'FERMI_GBM_FIN_INTERNAL', 'SUZAKU_LC', 'SNEWS', 'LVC_PRELIMINARY', 'LVC_INITIAL', 'LVC_UPDATE', 'LVC_TEST', 'LVC_COUNTERPART', 'AMON_ICECUBE_COINC', 'AMON_ICECUBE_HESE', 'CALET_GBM_FLT_LC', 'CALET_GBM_GND_LC', 'LVC_EARLY_WARNING', 'LVC_RETRACTION', 'GWHEN_COINC', 'AMON_ICECUBE_EHE', 'HAWC_BURST_MONITOR', 'AMON_NU_EM_COINC', 'ICECUBE_ASTROTRACK_GOLD', 'ICECUBE_ASTROTRACK_BRONZE', 'SK_SN', 'ICECUBE_CASCADE');
> 
> alter table "public"."gcnnotices" alter column notice_type type "public"."noticetype" using notice_type::text::"public"."noticetype";
> 
> drop type "public"."noticetype__old_version_to_be_dropped";

Yeah it's just suggesting that we drop the old version of the notice types ENUM and replace it with a new one with the correct values. The migration I added should accomplish the same thing (just adding a value to the existing type). 

Well, that was the idea but the test seems to have failed again so I'll look at it some more

**Comment by kmshin1397** [comment]
Ah I see, the ordering is off because the new value `SK_SN` is the second to last element in the package's enum so we can't just tack it on at the end like the migration is doing

**Comment by kmshin1397** [comment]
Ok should be good now

**Review by mcoughlin — APPROVED** [review]
Thanks for explaining that @kmshin1397. Seems good once green.

**Review by dmitryduev — APPROVED** [review]
LGTM!

**Pull request merged**
