### PR TITLE
Upgrade react and react-dom to v17

### PR DESCRIPTION
**Pull request by acrellin**

### CODE REVIEW

**Review by dmitryduev — APPROVED** [review]
Thanks for figuring this out, @acrellin.

**Comment by dmitryduev** [comment]
@acrellin still failed :(

**Comment by stefanv** [comment]
Surprising that the React upgrade is so smooth. Great!

**Comment by acrellin** [comment]
> Surprising that the React upgrade is so smooth. Great!

Unfortunately it's turning out not to be... :(

**Comment by acrellin** [comment]
Closing as stalled. Will open a new PR when we have more bandwidth for this (non-urgent) upgrade

**Pull request closed without merging**
