### PR TITLE
Duplicate sources flag on source page

### PR DESCRIPTION
**Pull request by acrellin**
This PR introduces a check for duplicates in the handler for fetching individual sources by ID. If any duplicates are found, an array of their IDs is included in the response. 

On the front-end source page, if any duplicates exist, a message appears indicating so with links to all possible duplicate sources.

dup_red_no_italics

Partially addresses https://github.com/fritz-marshal/fritz/issues/178

### CODE REVIEW

**Comment by mcoughlin** [comment]
@acrellin What fraction of your sources does this check get?

**Comment by acrellin** [comment]
@mcoughlin I just updated it from mag 15 (catches only two duplicates per 10k sources) to mag 18 (93 per 10k)

**Review by mcoughlin — APPROVED** [review]
Looks great post that update @acrellin.

**Comment by acrellin** [comment]
@mcoughlin It's pushed

**Comment by acrellin** [comment]
@mcoughlin What's the rationale for filtering out fainter objects?

**Comment by mcoughlin** [comment]
@acrellin My vision was that these were dominated by bright star PSFs moving the centroid of the subtractions around. But given these numbers, it seems clear that there wont be too many false positives.

**Comment by acrellin** [comment]
@mcoughlin So is there any reason to keep the minimum brightness filtering here?

**Comment by mcoughlin** [comment]
@acrellin no I think probably fine to remove, although I expect it to not change the numbers based on the hypothesis.

**Comment by acrellin** [comment]
It does change the numbers quite a bit -- with `mag <= 18` we catch 93 duplicates for 10k sources, and when removing that criterion it jumps to 301

**Comment by mcoughlin** [comment]
@acrellin In that case, can we look at the faint examples? I think that seems more likely to be truly different source for "normal" stars, where I would think that then we should have a criteria closer to our PSF limit (1 arcsecond).

**Comment by acrellin** [comment]
Removed magnitude filtering per a discussion w/ @mcoughlin

**Review by kmshin1397 — APPROVED** [review]
@acrellin Looks like test failure may be related but otherwise looks good

**Comment by acrellin** [comment]
Green now, with two approvals -- merging

**Pull request merged**
