### PR TITLE
Show cron job output in Dialog on click rather than Popover on hover on DB Stats page

### PR DESCRIPTION
**Pull request by acrellin**
cron_job_output_dialog

Closes https://github.com/skyportal/skyportal/issues/1736

### CODE REVIEW

**Comment by stefanv** [comment]
Could we use material UI list instead of `<ul>` for cron items?

**Comment by stefanv** [comment]
Otherwise LGTM!

**Comment by acrellin** [comment]
Sure, will do.

**Comment by acrellin** [comment]
> Could we use material UI list instead of `<ul>` for cron items?

@stefanv Done! Ready for review

**Review by stefanv — APPROVED** [review]

**Comment by acrellin** [comment]
Sole failure is unrelated (SEDM)

**Pull request merged**
