### PR TITLE
Edit shifts

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR makes it possible to edit shifts.

### CODE REVIEW

**Review by guynir42 — COMMENTED** [review]
Maybe add a small test (on its own or as part of one of the other shift tests)?

**Comment by Theodlz** [comment]
@mcoughlin, the save button is deactivated for me, even as super admin. I'm on it.

**Comment by Theodlz** [comment]
It's the "isInvalid" logic that is incorrect. A shift doesn't need a description or a required user number. So if a shift doesn't have one, you can't modify it here.

**Comment by mcoughlin** [comment]
@Theodlz I just removed that logic.

**Comment by Theodlz** [comment]
Great! I'm fixing some more stuff right now

**Review by Theodlz — APPROVED** [review]
LGTM. Failures are unrelated. Merging

**Pull request merged**
