### PR TITLE
Reference images

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR adds concept of reference images.

### CODE REVIEW

**Comment by mcoughlin** [comment]
@Theodlz Please try it out and fix as needed, also added DECam to the TNS list. We will need to add a line like: https://github.com/growth-astro/growth-too-marshal/blob/main/growth/too/tasks/tiles.py#L106
here(ish): https://github.com/skyportal/skyportal/blob/main/skyportal/facility_apis/observation_plan.py#L518

**Comment by Theodlz** [comment]
Will do!

**Comment by Theodlz** [comment]
@mcoughlin I am about to push some changes. Just to let you know, there are 3 incorrect rows in the DECam_Ref.csv, where the filter isn't an sncosmo one but instead is '6', and the limmag associated is 99.0. You might want to remove those. If so, let me know and Ill do it when I commit my changes.

**Comment by mcoughlin** [comment]
@Theodlz Yes please do!

**Comment by Theodlz** [comment]
> @Theodlz Yes please do!

I will. There is also no frontend to upload, so I'm trying to add one. Trying to fix some errors with parsing what the frontend sends the backend rn.

**Comment by Theodlz** [comment]
About to push frontend + removed incorrect DECam fields.

@mcoughlin I do see another error generating the fields from the frontend, which doesn't seem related to this PR, can yu maybe have a look? You're probably more familiar with this code than me. Here is the traceback of the error I get when I loved fields and regions from the frontend:
```bash
Traceback (most recent call last):
  File "/Users/theodlz/dev/skyportal/skyportal/handlers/api/instrument.py", line 1036, in add_tiles
    skyoffset_frames = coordinates.SkyCoord(
  File "/Users/theodlz/dev/skyportal/env/lib/python3.10/site-packages/astropy/coordinates/sky_coordinate.py", line 339, in __init__
    skycoord_kwargs, components, info = _parse_coordinate_data(
  File "/Users/theodlz/dev/skyportal/env/lib/python3.10/site-packages/astropy/coordinates/sky_coordinate_parsers.py", line 314, in _parse_coordinate_data
    _components[frame_attr_name] = attr_class(arg, unit=unit)
  File "/Users/theodlz/dev/skyportal/env/lib/python3.10/site-packages/astropy/coordinates/angles.py", line 655, in __new__
    self = super().__new__(cls, angle, unit=unit, **kwargs)
  File "/Users/theodlz/dev/skyportal/env/lib/python3.10/site-packages/astropy/coordinates/angles.py", line 140, in __new__
    angle = [Angle(x, unit, copy=False) for x in angle]
  File "/Users/theodlz/dev/skyportal/env/lib/python3.10/site-packages/astropy/coordinates/angles.py", line 140, in <listcomp>
    angle = [Angle(x, unit, copy=False) for x in angle]
  File "/Users/theodlz/dev/skyportal/env/lib/python3.10/site-packages/astropy/coordinates/angles.py", line 118, in __new__
    angle, angle_unit = form.parse_angle(angle, unit)
  File "/Users/theodlz/dev/skyportal/env/lib/python3.10/site-packages/astropy/coordinates/angle_formats.py", line 400, in parse_angle
    return _AngleParser().parse(angle, unit, debug=debug)
  File "/Users/theodlz/dev/skyportal/env/lib/python3.10/site-packages/astropy/coordinates/angle_formats.py", line 312, in parse
    raise ValueError(f"{str(e)} in angle {angle!r}") from e
ValueError: Invalid character at col 0 in angle 'Long,Ecl'
```

**Comment by mcoughlin** [comment]
Maybe the column headers are wrong?

**Comment by Theodlz** [comment]
> Maybe the column headers are wrong?

Maybe. Haven't looked into it yet, but found it surprising that it suddenly didn't work.

**Comment by mcoughlin** [comment]
I would just leave the frontend alone if it is what is blocking this from going in.

**Comment by Theodlz** [comment]
> I would just leave the frontend alone if it is what is blocking this from going in.

Oh no its not the frontend modifications. I just added something to upload the references. Whats blocking here is the fields upload nothing from the frontend.

**Comment by mcoughlin** [comment]
field_data = load_field_data(field_data)

And this line is failing?

**Comment by Theodlz** [comment]
> field_data = load_field_data(field_data)
> 
> And this line is failing?

Its failing later when generating the fields, but probably because this loading method didn't load it correctly. Working on it.

**Comment by Theodlz** [comment]
@mcoughlin looks like its working now. Let's wait for the tests to be green.

**Comment by mcoughlin** [comment]
@Theodlz good to go in?

**Review by Theodlz — APPROVED** [review]
LGTM. For some reason the API tests got cancelled? Otherwise can go in.

**Pull request merged**
