### PR TITLE
Issue 4819 gcn events too much white space

### PR DESCRIPTION
**Pull request by antoine-le-calloch**
#### This Pull Request fix this issue: GCN Events page: GCN Events list: too much white space and repeated info #4819 

- Updated and improved the display of Localizations and GCN Notices columns
- Removed the repetition of the ‘dateobs’
- Changed ‘overrides’ to ‘components’ for the getMuiTheme function due to its deprecation
- Added styles, removed margins, and added a tooltip to store the URL of the GCN notice
- Moved repeated code to new style functions
- Displayed the types of GCN notices
- Display only 3 localizations and 2 GCN Notices by default, with an option to expand them
- Removed the sort option for all columns except the ‘Date Observed’ column.

### CODE REVIEW

**Review by Theodlz — APPROVED** [review]
LGTM! Great work Antoine, very clean code too

**Comment by Theodlz** [comment]
Just making sure, did you sort the notices from most recent to oldest?

**Comment by antoine-le-calloch** [comment]
> Just making sure, did you sort the notices from most recent to oldest? @antoine-le-calloch

Done ✔

**Comment by antoine-le-calloch** [comment]
Some test didn't pass I'm on it !

**Pull request merged**
