### PR TITLE
Use GW190814 in demo data

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR uses GW190814 in the demo data in an attempt to keep the memory foot print down.

### CODE REVIEW

**Comment by Theodlz** [comment]
Should we use that also for the tests instead of the one we are using ? I think that one of the problems encountered by people is the app crashing when running tests multiple time when they involve ingesting events.

**Comment by mcoughlin** [comment]
Well the GCNEvent has a given dateobs so ingesting an event a second time doesn't make much sense.

**Comment by Theodlz** [comment]
I tried to do something similar before actually. You can maybe have a look at the branch anf compare with main to see what i needed to change to get it to work. Its here: https://github.com/Theodlz/skyportal/tree/lighter_demodata_gcnevent

**Comment by mcoughlin** [comment]
Personally it does not feel like a good use of time to me.

**Comment by Theodlz** [comment]
> Well the GCNEvent has a given dateobs so ingesting an event a second time doesn't make much sense.

What i meant is that for some reason, maybe because of the fact that it needs to generate thr contour and such, when running tests multiple times in a row it crashes the app, and maybe replacing an event we are using in the tests rights now by this "lighter" one could help ?

**Review by Theodlz — APPROVED** [review]
My comments aside (that can be the subject of another PR), this PR does its job. I'll merge once green, or if you think the failures are unrelated.

**Pull request merged**
