### PR TITLE
Pin baselayer

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by dmitryduev** [comment]
Something funky going on with pypi?

```
ERROR: Could not find a version that satisfies the requirement sncosmo==2.5.0 (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.8.2, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.4.0, 2.5.0)
ERROR: No matching distribution found for sncosmo==2.5.0
```

**Comment by stefanv** [comment]
No, this is a bug with sncosmo.  Newer versions of setuptools doesn't contain `use_2to3` any longer, so sncosmo has to remove it from their `setup.py`.

**Comment by stefanv** [comment]
FWIW, sncosmo has already been patched, but they need to make a release still.

**Comment by stefanv** [comment]
Fixed in setuptools 58.0.3, hopefully, so should be as simple as restarting the CI.  Let's see.

**Pull request closed without merging**
