### PR TITLE
Loosen pip requirements

### PR DESCRIPTION
**Pull request by dmitryduev**
Some pinned reqs are causing trouble: https://github.com/fritz-marshal/fritz/runs/1867100185#step:6:2691 (conflict with https://github.com/cesium-ml/baselayer/blob/master/requirements.txt#L7)
Putting out this fire in this PR, but I suggest to loosen more requirements, otherwise we'll likely encounter similar problems in the future.

### CODE REVIEW

**Comment by stefanv** [comment]
I think we agreed to pin to minor versions, so say something like `>=1.18,<1.19` for NumPy.  How does that sound?

**Review by stefanv — APPROVED** [review]

**Comment by dmitryduev** [comment]
@stefanv sure, np, as long as it does not case any issues. How about https://github.com/skyportal/skyportal/pull/1661/commits/2173555c295fd7737e97754bb3ccedaa244f5456 ?

**Comment by stefanv** [comment]
That's perfect, thanks.  I tend to be on the adventurous side when it comes to pinning (I prefer less of it), but I understand others' concerns about things breaking.

**Comment by dmitryduev** [comment]
Fixed the broken diff. Failure on the CI was unrelated (weather widget). @dannygoldstein should be mergeable.

**Pull request merged**
