### PR TITLE
add User.is_system_admin and Token.is_system_admin

### LINKED ISSUE #1220: Add `User.is_system_admin` property

### PR DESCRIPTION
**Pull request by dannygoldstein**
Fixes #1220

### CODE REVIEW

**Review by acrellin — APPROVED** [review]

**Comment by acrellin** [comment]
Should replace our existing checks with this new property in this PR, too

**Comment by stefanv** [comment]
LGTM, do you want to refactor other usages in this PR still?

**Comment by acrellin** [comment]
@dannygoldstein do you want to update the handlers to use this new property wherever applicable?

**Comment by dannygoldstein** [comment]
done

**Review by acrellin — APPROVED** [review]

**Pull request merged**
