### PR TITLE
Recent sources search bar

### PR DESCRIPTION
**Pull request by Carla802**
Hi @mcoughlin @Theodlz,
@lydie10 and I took care of the search bar that was needed in the recent sources tab. It searches the matching results (by id) with autocompletion.
This was one of the first tasks Sarah gave us.
Thanks in advance for your feedback ! 🚀

### CODE REVIEW

**Comment by mcoughlin** [comment]
@Carla802 I think the search bar doesn't seem to re-grab the recent sources consistent with the name you type in. I.e. on the demo data, typing in ZTF21, I would expect ZTF21aaqjmps to pop up (and otherwise the most recent sources with ZTF21 in the name).

**Comment by Carla802** [comment]
@mcoughlin We corrected this malfunction (commit "fixed result search"). Is it ok like this ?
Thanks for your feedback !

**Comment by mcoughlin** [comment]
@Carla802 

I started typing in your search bar and immediately the page crashed and I saw a large stack trace. It looks like your code needs more testing...

[14:23:36 js] TypeError: Cannot read properties of null (reading 'filter')
    at RecentSourcesSearchbar (webpack-internal:///./static/js/components/RecentSources.jsx:193:22)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at Paper (webpack-internal:///./node_modules/@mui/material/Paper/Paper.js:79:83)
    at div
    at div
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at Paper (webpack-internal:///./node_modules/@mui/material/Paper/Paper.js:79:83)
    at RecentSources (webpack-internal:///./static/js/components/RecentSources.jsx:412:23)
    at div
    at Resizable (webpack-internal:///./node_modules/react-resizable/build/Resizable.js:46:35)
    at DraggableCore (webpack-internal:///./node_modules/react-draggable/build/cjs/DraggableCore.js:134:5)
    at GridItem (webpack-internal:///./node_modules/react-grid-layout/build/GridItem.js:65:5)
    at div
    at ReactGridLayout (webpack-internal:///./node_modules/react-grid-layout/build/ReactGridLayout.js:98:5)
    at ResponsiveReactGridLayout (webpack-internal:///./node_modules/react-grid-layout/build/ResponsiveReactGridLayout.js:144:5)
    at WidthProvider (webpack-internal:///./node_modules/react-grid-layout/build/components/WidthProvider.js:77:7)
    at div
    at HomePage (webpack-internal:///./static/js/components/HomePage.jsx:403:17)
    at RenderedRoute (webpack-internal:///./node_modules/react-router/dist/index.js:715:5)
    at Routes (webpack-internal:///./node_modules/react-router/dist/index.js:1210:5)
    at div
    at LocalizationProvider (webpack-internal:///./node_modules/@mui/x-date-pickers/LocalizationProvider/LocalizationProvider.js:31:81)
    at InnerThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:22:70)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:44:5)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:41:5)
    at StyledEngineProvider (webpack-internal:///./node_modules/@mui/system/node_modules/@mui/styled-engine/StyledEngineProvider/StyledEngineProvider.js:28:5)
    at Theme (webpack-internal:///./static/js/components/Theme.jsx:27:33)
    at StyledEngineProvider (webpack-internal:///./node_modules/@mui/system/node_modules/@mui/styled-engine/StyledEngineProvider/StyledEngineProvider.js:28:5)
    at MainContentInternal (webpack-internal:///./static/js/components/Main.jsx:190:20)
    at InnerThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:22:70)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:44:5)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:41:5)
    at MainContent (webpack-internal:///./static/js/components/Main.jsx:181:19)
    at Router (webpack-internal:///./node_modules/react-router/dist/index.js:1142:15)
    at BrowserRouter (webpack-internal:///./node_modules/react-router-dom/dist/index.js:337:5)
    at ErrorBoundary (webpack-internal:///./static/js/components/ErrorBoundary.jsx:43:5)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connect.js:239:114)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:15:3)

**Comment by Carla802** [comment]
@mcoughlin I just retested it and it works for me locally... It also works for Lydie on her Skyportal. My branch is up to date and the code is the same. I don't understand why it is not working and how this error happens on your side but not on ours...

**Comment by mcoughlin** [comment]
@Theodlz Could you try testing locally and see?

**Review by mcoughlin — APPROVED** [review]
LGTM

**Pull request merged**
