### PR TITLE
Render login error page with error message

### PR DESCRIPTION
**Pull request by acrellin**
This PR implements a login error page upon unsuccessful authentication attempts. 

image

### CODE REVIEW

**Review by profjsb — CHANGES_REQUESTED** [review]
See comments, otherwise looks good.

**Comment by acrellin** [comment]
@profjsb I've removed the "Welcome to SkyPortal" banner. Please re-review

**Comment by acrellin** [comment]
@stefanv I've incorporated your suggestions to modify the PSA handler's write_error method successfully. See updated screenshot below: 

image

**Comment by acrellin** [comment]
Changed the login error page banner: 
image

**Pull request merged**
