### PR TITLE
Query for recent sources based on time saved

### PR DESCRIPTION
**Pull request by kmshin1397**
Closes Issue #963

### CODE REVIEW

**Comment by profjsb** [comment]
@kmshin1397 can you confirm that the failing tests are not related to this PR?

**Comment by kmshin1397** [comment]
The tests all passed for me locally, and GA and Travis are failing on different tests, so I don't think they are related to the PR. I'll try re-running the CI and see what happens.

**Comment by profjsb** [comment]
Small ask here: I think it would be good to add or modify a test for this -- with just the demo data I cannot see if the change has the desired effect.

**Comment by kmshin1397** [comment]
Sure, that makes sense. I'll add a test

**Review by profjsb — APPROVED** [review]
Great!

**Pull request merged**
