### PR TITLE
Move flaky frontend tests to dedicated file

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR moves the recent telescope, instrument and allocations front-end tests to a dedicated "flaky" file.

### CODE REVIEW

**Comment by stefanv** [comment]
This should really be a last resort.  Those pages are quite straightforward, so any reason we cannot fix the tests?

**Comment by mcoughlin** [comment]
@stefanv I think this might just be my inexperience. The tests run easily locally, I really do not understand what happens with the CI.

**Comment by stefanv** [comment]
At which lines do the tests break usually?

**Comment by stefanv** [comment]
(W.r.t. local vs remote: the only difference is that those machines are slow and have different viewport sizes (maybe)).

**Comment by mcoughlin** [comment]
On master it was these:

FAIL: skyportal/tests/frontend/test_telescopes_page.py:33 in test_telescope_frontend

        assert data['status'] == 'success'
    
        # check for API instrument
>       driver.wait_for_xpath(f'//span[text()="{name}"]')

skyportal/tests/frontend/test_telescopes_page.py:33: 

EDIT:
  $EDITOR +33 skyportal/tests/frontend/test_telescopes_page.py
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
FAIL: skyportal/tests/frontend/test_allocations_page.py:91 in test_super_user_post_allocation

        assert data['status'] == 'success'
    
        # check for API instrument
>       driver.wait_for_xpath(
            f'//span[text()[contains(.,"{instrument_name}/{name}")]]', timeout=20
        )

**Review by profjsb — APPROVED** [review]

**Pull request merged**
